### ISSUE TITLE
Expose small focused methods to work with React and like frameworks

### ISSUE THREAD

**Issue by ramnivas** [Dogfalo/materialize#1158]
To make Materialize work effectively with frameworks such as React, it needs to expose methods that work with individual DOM elements. Then (in case of React), component can call those methods in `componentDidMount` with individual DOM elements to give them the Materialize behavior.

In the current form, Materialize tends to operate at the whole page level. For example, https://github.com/Dogfalo/materialize/blob/0e924046c558538544f255e8375ff267963d7d62/js/forms.js#L6 goes over input elements in the whole document to install appropriate hooks. This is fine for static pages, but not for single-page apps. In my React components, I could call `Materialize.updateTextFields()` (see #1155). But this is inefficient, since changing any React component requires going over all input element even though most of them may not have changed.

Furthermore, it is not clear that methods such as `Materialize.updateTextFields()` are available for every component type. For example, there seems is no way to get text areas to animate correctly, since I couldn't find an exposed method that will let me do equivalent of https://github.com/Dogfalo/materialize/blob/0e924046c558538544f255e8375ff267963d7d62/js/forms.js#L85.

Ideally, Materialize exposes fine-grained methods such as `Materialize.updateTextField(element)`, `Materialize.updateTextArea(element)`, `Materialize.updateSelect(element)`. Then the aggregating methods such as `Materialize.updateTextFields()` can call them to preserve the current behavior for static pages, while offering a way to make it work for SPAs as well.

**Comment by lenaten** [comment]
+ 1

**Comment by phoenix741** [comment]
+1

I use backbonejs and marionette, and have some problem with text area, file input, labels, ... And when i read the js file, all is made considering that we have a static page, and is started when the page is loaded.

I need to launch the initialisation of some fields when the user change the page or when some part of the UI is updated.

**Comment by dshorowitz** [comment]
+1

**Comment by gow** [comment]
+1 for this. An interface to access the components via react would be super useful.

**Comment by andyhu** [comment]
What's the status for this issue?

**Comment by redbmk** [comment]
I have a partial solution I'm working on where the CSS looks at the value and placeholder attributes instead of an `active` class, and a little js updates the attribute to reflect the value on input changes. This would eliminate the need for updating select boxes as far as I can tell, but I'm having a hard time coming up with a solution for textareas.

It also would eliminate the need for calling `updateTextFields` on static pages that are prefilled, but does not work very well for dynamic pages with some frameworks (although I think React would work fine since it actually updates the attribute). My main concern with React is that both Materialize and React would be trying to modify the DOM, and React probably would manage it better than simply always updating on user input (since React works with diffs).

**Comment by redbmk** [comment]
Please take a look at PR #3253 and see if that helps at all (and if there are any performance impacts).

**Comment by Dogfalo** [comment]
This is the goal of our ongoing dev work in v1-dev branch
