### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by c2h5oh** [Dogfalo/materialize#1230]
Has anyone actually looked into supporting IE9? How much of Materialize is broken in IE9?

I know it's a horrible, horrible browser from the dark ages (hey, at least it't not IE6), but it's still the newest version of IE you can install on the oldest, still supported Windows version - Vista.

**Comment by skmasq** [comment]
+1

**Comment by DaEckster** [comment]
Considering Vista has only 2.9% of the market, and of that 2.9% it's likely most of them are using Firefox or Chrome, I think it'd be best to not bother with it.

I'm happy that Materialize's mixins file is only one mixin long.

**Comment by c2h5oh** [comment]
Combined IE9 market share (Vista, 7) is 2% http://www.w3counter.com/globalstats.php which is high enough for a lot of people to pass Materialize as a non-viable option - anyone building something that earns money can't sneeze on 1/50 market.

**Comment by DaEckster** [comment]
The WIndows 7 side of that will drop substantially when Windows 10 comes out. Still, I suppose it's worth looking at making it function, I wouldn't worry about making it pretty though.

**Comment by skmasq** [comment]
Although it's true about the market share, the North American business world still uses IE 9, I would say at least 30% of our clients still use it and we are obliged to support it in our web applications.

**Comment by c2h5oh** [comment]
Huh, it doesn't look that bad http://caniuse.com/#compare=ie+9,ie+10&compare_cats=CSS,HTML5

**Comment by Dogfalo** [comment]
You all missed the point of the original question. @c2h5oh wanted to know about how well Materialize works on IE9. We don't plan to add support for IE9 and if this is something that you need, you will have to look elsewhere.

**Comment by ciencia** [comment]
It "works", well enough. There are no smooth transitions, and no waves, though.

Also, [toasts](http://materializecss.com/dialogs.html) are broken: Element.classList is not supported. Why on earth you access directly the DOM instead of using jQuery? I even had to write a rewrite module to rewrite some snippets of code to make it work (to a minimal working state) on IE7 but you keep breaking it even more... I'm forced to stay on an earlier version because of this

**Comment by c2h5oh** [comment]
As long as it degrades gracefully it's good enough - thanks

**Comment by Dogfalo** [comment]
We don't support IE 7 and I don't see why it would be good to rely even more on jQuery

**Comment by ciencia** [comment]
@Dogfalo well, because you are using jQuery in the first place? Note that Element.classList is not supported in IE9 (we weren't talking about IE7) so it's broken in that browser. I'd prefer to use jQuery consistently in all the code rather than alternation between jQuery and direct access to DOM for tiny features like adding/removing a class name

**Comment by skmasq** [comment]
@Dogfalo I wouldn't say that you need to use jQuery as framework for selecting classes, but I would say that a small cross browser selector framework/class (e.g. sizzle.js or custom) would fill a substantial part of compatibility gap.

Like @c2h5oh  said, as long as it degrades gracefully and doesn't crash client it's good.

**Comment by c2h5oh** [comment]
@ciencia I agree about the need for consistency, but I don't necessarily agree that Query everywhere is the way to go, but that's just my personal preference. 

Anyway, according to github code search there are exactly 3 instances of `Element.classList` use in all of the code - 2 in toasts and 1 in waves - if we could get rid of them we'd get closer to graceful degradation in IE9.

**Comment by jndoy** [comment]
parallax and icons are also broken in ie9

**Comment by CelticParser** [comment]
...and 10

**Comment by Jossnaz** [comment]
the thing is... if it would look shit on IE9 i really would not care.

But it does not look shit, it actually doesn't work. You cannot fill a form any more.

**Comment by brunowebdev** [comment]
Is it worth forcing to update the IE user`s browser? Personally, I dont use MS no more and I dont understand the importance of IE & Edge updating

**Comment by Jossnaz** [comment]
@brunowebdev truth is, people forget. Not only do they forget, but they sometimes always used IE to begin with. People forget that EDGE is nothing else than IE. There is a movement of people saying MS Edge is the best browser. Haha :D why? because it starts faster... can you believe it? anyway, if 5% of all people still use IE9, that means 5% of people cannot use the page. 5% less sales etc. Not acceptable sadly

**Comment by webdesignofpassion** [comment]
Here is a parallax fix for IE & Edge. 
I hope it helps you further.

https://github.com/webdesignofpassion/materialize-parallax-chopping-fix/blob/master/app/scripts/parallax-chopping-fix.js
