### ISSUE TITLE
Striped table should ignore rows with .hide class

### ISSUE THREAD

**Issue by hfrid** [Dogfalo/materialize#1257]
When working with filtering tables, if I hide a row in a striped table I break the even odd coloring and naturally end up with two rows of the same color. However, this persist even if I remove striped class from table and the re-apply the striped class. To me it would make more sense if rows with .hide was ignored.

**Comment by krisDOTco** [comment]
This, while reasonable, may require something a little more than what Materalize does. It seems you may have to do something using javascript because you need to be able to totally remove an element (to allow the element flow to continue). The styling rule works like this:

table.striped tbody tr:nth-child(odd) {give grey background colour}

If you perform a simple display:none on the fourth row for example, the CSS still considers it as the second even row because the element still actually exists. Either that, or having custom CSS classes and re-applying those using javascript every time you fire whatever filtering functionality you're using.

Do you have a demo that we could apply some real-world scenarios to?

**Comment by Dogfalo** [comment]
Yes, this can't really be done with just CSS. You will have to handle this yourself.
