### ISSUE TITLE
floating action button on click

### ISSUE THREAD

**Issue by filippomartini** [Dogfalo/materialize#1421]
Is it possible to trigger the floating Action button on click? Becouse hover doesn't work on mobile... Thanks!

**Comment by UriahsDev** [comment]
I just realized that it doesnt accept clicks, i did add the clicking capability by adding the class ` waves-effect waves-light` to the <a> tag, this will make the button clickable. However, for showing the icons, clicking it did not work.

I am just going off my head here but you could create this on mobile yourself. The button divs will have to be hidden on large and medium screens and floated right. You could use this button and float it right  `<a class="btn-floating btn-large waves-effect waves-light red"><i class="mdi-content-add"></i></a>`

You would use `onclick` on the <a> tag to execute this piece of js http://jsfiddle.net/rathoreahsan/vzmnJ/ the buttons will be visible once the first button is clicked...from there you could add in your custom easing and fading.

I didnt really go in depth but im assuming since you're using materialize and signed up on github you could do this. Hopefully the devs incorporate this straight into materialize.

**Comment by Flaburgan** [comment]
The example describes [in the doc](http://materializecss.com/buttons.html) works well for me on mobile.
