### ISSUE TITLE
Hammer.js not found

### ISSUE THREAD

**Issue by chaitanyambilgikar** [Dogfalo/materialize#1472]
I'm getting a hammerjs.js not found error when I import the jquery and the materialize .js
```
Uncaught Error: Script error for: hammerjs
http://requirejs.org/docs/errors.html#scripterror
```
I am using requirejs to get my js files.
What am I doing wrong?

**Comment by ktmn** [comment]
Well it just didn't come with the npm release if I understand correctly. Same with "picker.js" which it looks for in its own directory. I installed them separately.

    npm i hammerjs
    npm i pickadate

Hammerjs I was able to just import before materialize and it works.

    import hammerjs from 'hammerjs';
    import Materialize from '../node_modules/materialize-css/bin/materialize.js';

For picker.js how ever I couldn't figure it out other than copy paste the file to the bin directory so materialize.js finds it. I use gulp for that.

    gulp.src('node_modules/pickadate/lib/picker.js').pipe(gulp.dest('node_modules/materialize-css/bin'));

Importing materialize.js like shown above, instead of using the cdn file, it also fixed my problem in issue #1466.
