### ISSUE TITLE
TABS how to trigger  next tab with <a>/<button> element

### ISSUE THREAD

**Issue by vAhyThe** [Dogfalo/materialize#1545]
Can somehow after click and continue to next tab ??
Thx much

```
<div class="col s12">
    <ul class="tabs">
        <li class="tab col s4"><a href="#test1"  class="active">tab1</a></li>
        <li class="tab col s4"><a href="#test2">tab2</a></li>
        <li class="tab col s4"><a href="#test4">tab3</a></li>
    </ul>
</div>

<div id='test1' class="col s12">
    <a href='#test2' >continue</a>
</div>
<div id='test2' class="col s12"></div>
```

**Comment by acburst** [comment]
I'm confused on what you are asking? Do you not know how to use Tabs? More clarification would be helpful

**Comment by vahy** [comment]
After you click on ```<a href="">continue</a>``` then will open next tab & also that tab will be active.
Is better or i should be more specific ?? thx

**Comment by onerinas** [comment]
@acburst vahy needs help on triggering tab from a href link ( outside .tabs)

**Comment by Qwindoo** [comment]
Hello, same issue here. Is there a way to trigger a tab change from a link? I couldn't find any from the documentation.

My typical use case is an HTML form split into several tabs (kind of like an installation wizard). From the bottom of each tab, I want to have links/buttons that when clicked switches to the previous/next tab when applicable.

The simplest way would be to be able to write `<a href='#another_tab' >continue</a>` anywhere in the page and have it make the tab switch based on the passed ID. Is it possible to do to date? I'd be glad to help implement it otherwise :)

**Comment by tomscholz** [comment]
You can use the` select_tab` method and a little bit of js to achieve that. Alternatively have a look [here](http://materializecss.com/tabs.html#methods)

**Comment by Dogfalo** [comment]
1.0 has instance methods for this
