### ISSUE TITLE
Disable tooltips

### ISSUE THREAD

**Issue by valerio-bozzolan** [Dogfalo/materialize#1629]
Is there any method to disable/remove a tooltip programmatically?
(I've not seen any method in the source code to remove them.)

**Comment by janpieterz** [comment]
Hi @valerio-bozzolan 

This seems to work: $(".tooltipped").off("mouseenter mouseleave");
Obviously replace .tooltipped with your own (specific) selector.

In case you're in the mood, making a pull request and editing the tooltip.js with a function so that the logic stays within that component will probably be really appreciated (I'm not a maintainer of this library).

**Comment by Dogfalo** [comment]
Added in 30b2e1d

**Comment by Luis16287** [comment]
`$('.tooltipped').tooltip('remove');
`

[removal section](http://materializecss.com/dialogs.html)
