### ISSUE TITLE
Page return to the top after close modal

### ISSUE THREAD

**Issue by LperezGT** [Dogfalo/materialize#1662]
When click in close button on modal the page return to the top, i trying with href and data-target.
```
<img id="imgZoom" class="modal-trigger" data-target="modalSVC01" src="../Folder/Folder/img.png" />
```

event the button and the link doesnt work when close modal.

Working with VS2010, asp.net c#, Materializer 0.97 and Jquery 2.1.4

**Comment by acburst** [comment]
Can you post an example codepen?

**Comment by philipraets** [comment]
If you replace the a tag with button type="button" then the page doesn't jump back to the top. The jumping happens because the href points to "#!".
Replace 
 <a href="#!" class=" modal-action modal-close btn-flat">CLOSE</a>

with
<button type="button" class="modal-action modal-close btn-flat">CLOSE</button>

**Comment by LperezGT** [comment]
Thanks, it was the href="#!". I think the attribute href was necesary for that event, following the example of modal fixed footer in http://materializecss.com/modals.html. Really great @philipraets both solution work.. :dancer:
