### ISSUE TITLE
"$('select').material_select();" - Issue

### ISSUE THREAD

**Issue by fcgomes92** [Dogfalo/materialize#1686]
Hi. When I use the select box dynamically in a form, in my case it is a simple gender select, whenever I create a new form and call '$('select').material_select();' another select box appears.
I thought it was related to the fact that I'm using each dynamic form inside a collapsible element, but when I changed the class to 'browser-default' everything worked fine.
I took a look around but didn't find anything like this, if it's an old issue or something like that I apologize xD

Here is what it looks like when I add a second form. The upper select box doesn't work, just the bottom one.
![screenshot from 2015-07-07 01-34-13](https://cloud.githubusercontent.com/assets/6561278/8538790/7422b3e4-2448-11e5-951c-35cb24148dab.png)

Thanks (:

**Comment by carlosperate** [comment]
This was an issue resolved a long time ago (https://github.com/Dogfalo/materialize/issues/819, https://github.com/Dogfalo/materialize/issues/452), are you sure you are using the latest version?

Based on the extra caret added at the top, I would assume you are using 0.97.0 as that was an issue on that version (https://github.com/Dogfalo/materialize/issues/1570), so it should be working. If you are changing the select forms, are you sure you are destroying the old one first? 

`$('select').material_select('destroy');`

Otherwise please crate a codepen with an example of your issue.

**Comment by ahmadfikrizaman** [comment]
Encounter the same problem on 0.97.0..

```javascript
            $('select').material_select('destroy');

            $.each(content, function(index, value)
            {
                $("#" + index).val(value);
            });

            $('select').material_select();
```

**Comment by ahmadfikrizaman** [comment]
owh.. sorry @carlosperate .. just saw the #1570
