### ISSUE TITLE
background-color breaks Parallax

### ISSUE THREAD

**Issue by omin** [Dogfalo/materialize#1732]
I'm trying to use Parallax on my landing page while having a sticky footer; however, I have light grey background and the sticky footer fills up the remaining space with white. In order to match this, I added light grey `background-color` to `<main>` but this breaks parallax.

**Comment by acburst** [comment]
Can you post a codepen?

**Comment by OminStyle** [comment]
Of course :)

https://jsfiddle.net/OminStyle/5hrpcp1j/

**Comment by acburst** [comment]
The issue I think is with your flexbox styles

**Comment by OminStyle** [comment]
The styles are from http://materializecss.com/footer.html.

**Comment by Cypher1** [comment]
This still is an issue. Anyone have a fix?

**Comment by tomscholz** [comment]
I can't seem to reproduce it. I close this issue for now. If anyone post a codepen that can reproduce the issue we can reopen.

**Comment by Xandaros** [comment]
I just ran into this issue. We had `background-color` set for html, body and main. Turns out, if you set a background colour on both html and body, it doesn't show properly: https://codepen.io/Xandaros/pen/MWYwRYy

Funnily enough, this seems to only affect the first parallax on the page (though I can't reproduce that behaviour in codepen). Took me absolute ages to debug.
Setting it on either html or body, but not both, also causes no issues.

**Comment by supergnaw** [comment]
I also had this issue, but for all .parallax-container divs instead of just the first. I tried applying the background color classes to various things per this thread without success. The fix for me was changing the z-index of the .parallax-container because the background image of the .parallax-container was being shifted behind the parent div somehow. I hope this helps someone in the future.
