### ISSUE TITLE
Problem with special characters in form select using materialize style

### ISSUE THREAD

**Issue by Y0lk** [Dogfalo/materialize#1783]
This line of code is problematic if you have special characters such as double quotes in your option name : 
`var $newSelect = $('<input type="text" class="select-dropdown" readonly="true" ' + (($select.is(':disabled')) ? 'disabled' : '') + ' data-activates="select-options-' + uniqueID +'" value="'+ label.html() +'"/>');`

Since the html of the option is added directly as the value of the input, it breaks if there are double quotes.

**Comment by carlosperate** [comment]
When submitting some code, please provide in a complete format, otherwise somebody else will have to write the rest of it to test it. Also, as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md), it would be even better if a codepen is submitted with an example illustrating the issue.

In the example you are providing, unless I'm not understanding you incorrectly, your issue arises because you are creating a string to create an HTML element (I assume to then append to the DOM as inner HTML). If that is the case, then it's not really the Materialize framework that fails to sanitize the input, but the fact that you'd be adding data directly into a string without ensuring it is sanitised. If I am mistaken, could you provide a working example?

**Comment by Y0lk** [comment]
Sorry if that wasn't very clear. Here's a codepen showing the problem : http://codepen.io/anon/pen/MwPQwv

Basically, when you have double quotes in an <option> 's text, even if they're written as entities &quot;, it breaks when Materialize initializes the select and tries to put the option's text in the value attribute of its input text.

The line of code I was refering to is line 345 in forms.js where Materialize creates that input text with the value. 
Here's a screenshot in the inspector. Hope that was more clear.
![capture](https://cloud.githubusercontent.com/assets/1523444/8890278/f84ca452-32c8-11e5-9e8d-5f8d2bc8d139.JPG)

**Comment by carlosperate** [comment]
Right, I see now that the code posted was [forms.js#L345](https://github.com/Dogfalo/materialize/blob/60131b37e132c6523c1a79897f117c71f2ab11ee/js/forms.js#L345) as you've pointed out, which isn't properly sanitising the data to be embed it into the html.

**Comment by acburst** [comment]
fixed in 1b92fb2
