### ISSUE TITLE
Modal conflict with bootstrap

### ISSUE THREAD

**Issue by newjie** [Dogfalo/materialize#1803]
Modals are using class .modal, which bootstrap uses too. So if the page also includes bootstrap, the modals won't display materially. +

**Comment by carlosperate** [comment]
I wouldn't recommend the use of bootstrap together with Materialize, as there are a few feature overlaps. At this point I doubt there much that can be done about this specific issue, as editing that name would be a breaking change.

**Comment by guoyoujin** [comment]
@carlosperate Is there any way to solve this problem, I also used in the project to the bootstrap and the package, there are some styles of conflict

**Comment by Dogfalo** [comment]
You can just rename the function

**Comment by guoyoujin** [comment]
@Dogfalo Ok, I'll give it a try, according to this method should be useful to you, but may face is that many properties, have to rename, it may not be a good way, but now can only be the case, thank you for your answer

**Comment by Dogfalo** [comment]
Adding bootstrap and materialize is probably causing more problems than you might realize at first and is not recommended.

**Comment by newjie** [comment]
d

**Comment by blandman** [comment]
This is so cumbersome. Could there at least be alias functions for use cases where bootstrap is needed?

I've gone into the Materialize.js file and changed the dropdown function name like this
```
$.fn.dropdownMat = function (options) { ... (line 623)
```

Found and replaced all instances of dropdown() inside this file too. Works fine side by side with Bootstrap now...

I believe this function should be called menu or something similar, since this is the Material namespace equivalent.
