### ISSUE TITLE
Material Icons vs Material Design Icons

### ISSUE THREAD

**Issue by syed-haroon** [Dogfalo/materialize#1824]
Where can I find Icon chart if I need to use icon in this way "mdi-ICON-NAME" ?
Please refer the below URL for full description of my question:
http://stackoverflow.com/questions/31698485/material-icons-vs-material-design-icons

**Comment by carlosperate** [comment]
The `mdi` type icons are being phased out for the official google sources, that's why you won't find the old chart in the documentation. A complete list of the new icons can be found in https://www.google.com/design/icons/ .

**Comment by syed-haroon** [comment]
@carlosperate then why not just delete all the <addr>mdi</addr> icons and css defined as new icons are already offered by google, isn't it?

**Comment by carlosperate** [comment]
Because that would suddenly break all the user implementations, so this way it can be phased out gradually, giving people time to update their icons.

**Comment by jacobq** [comment]
Could someone explain why support is being dropped for the `mdi-*` style? I was using the ones from https://materialdesignicons.com/ since they include many more (community contributed) icons, which I would like to use. Is it just that this framework is aiming to stick with the official google sources as closely as possible?
