### ISSUE TITLE
Make animations optional

### ISSUE THREAD

**Issue by baraamashaal** [Dogfalo/materialize#1877]
could the animations be optional ? 

in my case i want to make may customize one for the dropdown animation
how can i disable the default one ?!

**Comment by nibelungen** [comment]
+1 on this - running materialze on an raspberry 2 is not really fun because of the animations.... Looks really strange - would be great to disable the animations.
Any other hints to use materialize with an raspberry and chromium? Midori doesnt work at all - it hangs
while loading the scripts.

best regards

**Comment by stylefieber** [comment]
+1 the dropdown button for example is terrible on mobile

**Comment by stylefieber** [comment]
Added animation control to dropdown:
https://github.com/stylefieber/materialize/pull/2

two options: animationIn and animationOut.
Set both to false and you have no animation.

**Comment by nibelungen** [comment]
@tomscholz why was this issue closed??

**Comment by fega** [comment]
@tomscholz for me this is a valid topic

**Comment by crtag** [comment]
Is there any progress on this, it's been 2 years now since the start.

**Comment by Dogfalo** [comment]
We aren't completely closed to the idea, but its very low on the priority list

**Comment by Dogfalo** [comment]
I think this can largely be handled just by setting transition to 0 duration on the plugin calls. This also does not seem to be a very popular request so we will not be adding any additional support for it.
