### ISSUE TITLE
Pushpin doesn't respect the footer's area

### ISSUE THREAD

**Issue by rogeriotaques** [Dogfalo/materialize#1920]
The pushpin doesn't respect the limit of footer's area, which means that when pushpin block is long enough and page isn't so long, whenever page reaches its end, the pushpin block surpass the footers, sometimes covering footer's content, sometimes mixing it and turning it unreadable.

Have a look on the pushping sample page at materializecss.com
http://materializecss.com/pushpin.html

To reproduce this bug, please do scroll the page till the end.

I suggest that pushpin may be aware of its scrolling limit, leaving its fixed position as soon as a block (such as footer) be reached and getting fixed again as soon as page start to scrolling up and the end of pushpin block touch the end of visible window.

**Comment by isaachinman** [comment]
@rogeriotaques I've just come across this issue too, but you're fundamentally misunderstanding what is going on here.

The pushpin function takes a "bottom" option:

    The distance in pixels from the top of the page where the elements stops being fixed. (Default: Infinity)

The real problem here for the Materialize guys is that if you are specifying bottom as a pixel count instead of a div id (whose height sets offset), we're going to need media queries. Footers are taller at small and medium breakpoints. As @rogeriotaques pointed out, the pushpin example in the docs is broken on small/medium breakpoints.

Alternatively, I think using a div id to get height and use this as offset is a better approach, but I suppose you'd have to add a window resize listener.

**Comment by acburst** [comment]
Fixed in e8b16c6. Wow, i've procrastinated on this bug for so long >.<
