### ISSUE TITLE
Documentation of the avaible options

### ISSUE THREAD

**Issue by NetanelBasal** [Dogfalo/materialize#1958]
There is a place where i can see what options i can use, for example for buttons what classes i can apply to sizes? big, small ? colors?
There is great examples in your site but to see how i can use certain things i need to inspect element.

**Comment by carlosperate** [comment]
Except for colours, which has a straight forward use (info can be found in the [colours documentation](http://materializecss.com/color.html), I believe the buttons documentation page contains all possible options. Could you specify which option is demonstrated and not documented in the page so that the documentation can be updated?

**Comment by NetanelBasal** [comment]
For example here:

http://materializecss.com/preloader.html

Preloader: 
What is the names of the size classes - like "big"
Indeterminate -
I can change the color with another class?
