### ISSUE TITLE
Radio and Checkbox Inputs are not tabbable

### ISSUE THREAD

**Issue by shaun3141** [Dogfalo/materialize#1979]
When creating a form, if you attempt to tab through it which I think is fairly common, it will skip over all radio buttons and checkboxes and go to the next textarea, select, etc. input. 

As an example, look at the main site: http://materializecss.com/forms.html

Click the first input field, and then start tabbing like you would on any form. It will completely skip the checkbox and radio button section. I am building a questionaire site and this is proving to be quite the headache.

**Comment by Dogfalo** [comment]
As a temporary fix you can remove visibility:hidden

On Sun, Aug 30, 2015 at 7:52 PM, shaun3141 <notifications@github.com> wrote:

> When creating a form, if you attempt to tab through it which I think is
> fairly common, it will skip over all radio buttons and checkboxes and go to
> the next textarea, select, etc. input.
>
> As an example, look at the main site: http://materializecss.com/forms.html
>
> Click the first input field, and then start tabbing like you would on any
> form. It will completely skip the checkbox and radio button section. I am
> building a questionaire site and this is proving to be quite the headache.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dogfalo/materialize/issues/1979>.
>



-- 
Doggy sends his greetings from Mars.

**Comment by santiestra** [comment]
Yes, removing `visibility: hidden` from the input makes.

And I also wanted to make the checkbox different while being focused so I added:

    [type="checkbox"]:not(:checked):focus + label:before {
      border-color: $color-green;
    }

    [type="checkbox"]:not(:checked), [type="checkbox"]:checked {
      visibility: visible;
    }

**Comment by Dogfalo** [comment]
Fixed in 20eb814

**Comment by shaun3141** [comment]
Looking forward to seeing this! Thanks - we created an entire dating site using everything we could from Materialize - www.swirlmingle.com if you want to check it out.

**Comment by marcorivm** [comment]
any fix for when the inputs are previously hidden and then made visible?

**Comment by NewBo1234** [comment]
Hello,

I'm working on accessibility features and while I have truly loved Materialize for a long time, this is turning into a pain.

The fix referenced in this is no longer working and I cannot see all of the changed code.  Please please please don't just put a build version--PUT THE ACTUAL CODE.  We are no longer able to see half of the good work you guys put in this.

Sorry -- I'm working with 97.5 because the accessibility came before updating and doing all the break fixes that upgrading causes.  TONS of BREAKS.  I cannot upgrade and now I cannot see what you did to fix the problem.

Please please put something more than @#$ASDF as a reply and closing the ticket.  It is very important to those of us who are coming along later.  

Please post the actual answer.

Newbo
