### ISSUE TITLE
materialboxed class inside of card error

### ISSUE THREAD

**Issue by tdhz77** [Dogfalo/materialize#1997]
<div class="card"> //card small, medium large result in same
    <img class="materialboxed" width="650" src="images/sample-1.jpg">
    </div>

The image loads as expected in the popover, however the image is only the size of the original card, so it doesn't expand. 

This behavior does not occur when I do the following.

    <div class=z-depth-1">
    <img class="materialboxed" width="650" src="images/sample-1.jpg">
    </div>

Side note: You cannot use the activator class on a card with the materialboxed class too. 

I wanted the user to be able to click on the image and it expand using materialbox, but if they wanted more details could hit the icon to scroll card up.

Any help is greatly appreciated?

**Comment by acburst** [comment]
You have to disable overflow: hidden on card

**Comment by SimulatedGREG** [comment]
I'm having a similar issue, but instead of using a card I'm trying to use the slider. So if a user clicks a slide it expands using materialboxed. Putting the ``` .materialboxed``` class on the ```<img>``` tag opens the view, but the image isn't there; it just shows the gray background. I've had some success putting the class on the ```<li>``` tag, but this method breaks the slider navigation using the indicator dots. Somehow, they get placed behind the images, so in turn I pushed them down with some CSS, but the actual function of clicking them is bugged.

```html
<div class="slider z-depth-1 hoverable">
  <ul class="slides">
    <li class="materialboxed"><img ng-src="//lorempixel.com/500/400/city/1"></li>
    <li class="materialboxed"><img ng-src="//lorempixel.com/500/400/city/2"></li>
    <li class="materialboxed"><img ng-src="//lorempixel.com/500/400/city/3"></li>
    <li class="materialboxed"><img ng-src="//lorempixel.com/500/400/city/4"></li>
  </ul>
</div>
```
```javascript
$('.materialboxed').materialbox();
$('.slider').slider({
  interval: 5000
});
```

Any suggestions are appreciated.

**Comment by dirkpennings** [comment]
@acburst when you disable overflow: hidden it causes the ".card-content" to appear from beneath the card box instead of within the card box (because now the overflow property is gone) so that's no solution (tried it myself :wink:)

I think the issue is caused by different stacking contexts
[This article](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) explains it nicely

**Comment by acburst** [comment]
If you havent checked out this commit: 37c9d79, I added code to materialbox to dynamically remove overflow: hidden from parents when opened, and then subsequently re adding overflow: hidden back to those elements. Try this out.
