### ISSUE TITLE
slider not working, showing grey background

### ISSUE THREAD

**Issue by bhushangoel** [Dogfalo/materialize#2010]
I am using v0.97.0 and as per the documentation I am using slider, but it is showing grey background only.

**Comment by carlosperate** [comment]
Documentation code is working correctly: http://codepen.io/anon/pen/avONJL
Please provide a codepen illustrating your issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file.

**Comment by bhushangoel** [comment]
not this slider, I am talking about carousel

**Comment by carlosperate** [comment]
Once again, it would be useful if you could provide a codepen illustrating your issue as indicated in the [contributing](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) file.

**Comment by wissile** [comment]
It's pretty easy! Make sure you materialize css and js loaded along with jquery. then initiliaze it in a separate script.js file or at the end of the doc right before the end of boday tag place this code:
<script>
$(document).ready(function(){
      $('.slider').slider({full_width: true});
});
</script>
made an example at this link: https://jsfiddle.net/nLdcjcdt/
Hope it helps

**Comment by Dogfalo** [comment]
Thanks @wissile for the demo.

**Comment by maheshbvv** [comment]
even materialize website has this bug, can someone help me to fix this? 

![image](https://cloud.githubusercontent.com/assets/8593309/15146339/d3a968a0-16cb-11e6-9e94-036fe039dc7c.png)

**Comment by dr-kibe** [comment]
Hello there
The problem is due to uninitialized js. Insert this at the end of your html.
<script>
            $(document).ready(function () {
                $('.slider').slider({full_width: true});
            });
 </script>  
If you wish to put your own images then you've also got to take care, some dont load as expected, guess due to their sizes.
For more > http://stackoverflow.com/questions/34560005/materialize-css-slider-not-working

**Comment by pradanna** [comment]
@borenho oh thanks man, it realy works

**Comment by eriksturesson** [comment]
I have the same issue. You seem to have given really good tips, thanks @borenho. I didn't work for me though :(. I'm a noob but I have managed to get the .js-file to speak with the .html and .css file otherwise. Does not work anyway. I tried to put your script-tag within the html-document in the end of the body ofcourse.
