### ISSUE TITLE
Site search implementation

### ISSUE THREAD

**Issue by thisninja** [Dogfalo/materialize#2055]
Hey. I'd like to see site search to have quick access to content like on [foundation docs page](http://foundation.zurb.com/docs/).

If there are any chances that it will be accepted I'd like to help with that. :sunny:

**Comment by acburst** [comment]
We were thinking of doing some basic site search but because our docs are just static pages we didn't really know of a good way. If you have any suggestions or want to try implementing something in a pull request we'd love to see it.

We were looking at something called lunr.js which is a basic client side javascript search which would be a good place to start. http://lunrjs.com/

**Comment by acburst** [comment]
Finished in 15059ed
