### ISSUE TITLE
What about adding a _spacing.scss ?

### ISSUE THREAD

**Issue by joelataylor** [Dogfalo/materialize#2132]
Hi there - was curious if you'd be interested in adding a spacing Sass file that specified classes to add margin and padding at various browser widths:

```
.pd { padding: 1rem }
.pd-sm { padding: .5rem }
.pd-lg { padding: 1.5rem }
.pd-bottom-lg { padding-bottom: 1.5rem }
.pd-bottom-lg-at-medium-and-up { ... }
.no-pd { padding: 0 }
.no-pd-at-large-and-up { ... }
....
```

Thoughts?

**Comment by acburst** [comment]
This is an interesting idea. We have a bunch of stuff on our plate for the next release but we would love to see a pull request with some ideas.

**Comment by msolters** [comment]
This is a great idea.  I've noticed a lot of developers abusing `<p>` tags because they make for easy spacing -- but this will break in some browsers such as Firefox because `<p>` is technically *only* supposed to be used for inline content. Firefox will actually force close your paragraphs by injecting a `</p>` as soon as it sees a line break.

I bet we'll see much less of that antipattern and more responsible use of `<div>` once it becomes easy to quickly add some responsive spacing to them with a quick semantic class.
