### ISSUE TITLE
Help! Validation 

### ISSUE THREAD

**Issue by masterpowers** [Dogfalo/materialize#2204]
Ive been Looking a Way to Validate
Password Confirmation ...
i know there is a validate class for required and length and minlength
But is there a  Password confirmation validator?
I tried using Jquery validator and it messes up Label with Error and Success Message...
It mixed up.
Hope if someone has done validation using materialize hope you can share how you do it

**Comment by SuperDJ** [comment]
To validate a password never rely on HTML, JavaScript / jQuery but use PHP

**Comment by SirusDoma** [comment]
I agree with @SuperDJ , Just in case you are wondering (and you might be know), HTML and Javascript are client-sides (except we are talking node.js)

It give security holes on validation, the user may modify / inject the javascript on validation code, its safer to use server sides validation (PHP, ASP or node.js), because validation performed in server-sides.
