### ISSUE TITLE
AngularJS(Primary) materialize or angular material or material design

### ISSUE THREAD

**Issue by AbhaySuchak** [Dogfalo/materialize#2248]
i am using materialize css for my site for design purpose and i am using angularjs to provide fair flexibility to my site but some property of materialize(Select,date-picker,radio-button) did not insert while inserting query it takes blank values from ng-model and when i am talking about radio button so it takes 2nd value when i select 1st or reverse.

So it is my straight Question is..

what is the scope of using materialize or material design or angular material with AngularJS because my priority is to use AngularJS with any of above google design.

please responds as soon as possible

**Comment by acburst** [comment]
There are many bugs with angular and due to our small team, (and our relative inexperience with angular) we can not catch all of them. We also don't prioritize these bugs over bugs that affect everyone. We are always looking for more contributors who are experienced with frameworks like Meteor and Angular. But at the moment, issues regarding specific frameworks may take longer than usual to fix. If you are experiencing major problems, I would suggest just using angular material for now.

**Comment by diegoaguilar** [comment]
@acburst I'd love to know the status of Angular used related bugs, did you get any updates in particular submitted issues?

**Comment by rthomson83** [comment]
I've been using this in an angular project and haven't seen any real issues so far. 
Using angular it's just a matter of hooking up the init methods for selects etc in a directive. This is due to the fact the init stuff is only run once on DOM ready so when working with angular views etc where elements are added dynamically, using directives to run the init for that element is all that's needed.
