### ISSUE TITLE
touchStart event closes dropdown menu without triggering action

### ISSUE THREAD

**Issue by theberengersniper** [Dogfalo/materialize#2413]
Hi guys,

There seems to be an issue that was introduced in 0.97.2 where the touchStart event interferes with dropdown menus.

Observed behaviour:
Dropdown menus are dismissed without triggering an action when the user taps a menu item.

Expected behaviour:
Dropdown menus are dismissed along with an action being triggered.

I appreciate this is likely a duplicate of #2212, however that issue hadn't received any comments from development. This is turning out to be something of a show-stopper in my project.

**Comment by bmcbride** [comment]
:+1: This appears to be most noticeable on iOS Safari and doesn't seem to be much of an issue on Android/Chrome.

**Comment by niwasmala** [comment]
Currently I'm working on hybrid apps using cordova and materializecss on iOS. I'm having similar problem for dropdown input, on touchStart. Is there any way to prevent dropdown closed? I already try attach touchStart and prevent default, but it failed, dropdown still closed. Any hints would be helpful. Thank you.

**Comment by future-boy** [comment]
Hi everyone,

I ran into this recently on devices and after a little investigation the problem seems to be the event bindings on the dropdown. The closing of dropdowns were previously bound to the 'click' event as you would expect, but in 0.97.2 it appears the 'touchstart' event was added to this binding and I'm not sure of the reasoning behind that, because devices and their browsers do actually fire the 'click' event for taps in all the cases I have tried (so the dropdown would still close, albeit a litte later in the event heirarchy).

So to give an example, let's say we click a given node which opens the dropdown (the opening ONLY has the 'click' event bound by the way). Then the dropdown is shown and the close events are bound (both 'click' and 'touchstart' this time). Now if I'm on a touch device, as soon as I try to tap any type of our buttons inside the dropdown, the 'touchstart' fires first, the dropdown closes and (assuming you have your own actions bound to clicks) the button never gets the click event because technically you're no longer on the button for the 'click' event (the dropdown has already closed as of the 'touchstart').

The best fix for this is probably a revert of commit 2456c2e9047b9c3b724913af93603c8238d58c3e, although there may be reasons behind that addition that I'm not seeing here, but that's the commit where the issues started.

Hope this helps, thanks.

**Comment by samba** [comment]
I'm seeing some trouble with it in Android on iOS as well, version 48.0.2564.104.

**Comment by zhaoyao91** [comment]
I have created a [pr ](https://github.com/Dogfalo/materialize/pull/2953)to fix this problem. I hope somebody can help me test it.

**Comment by VioletaCalvo** [comment]
Hi!

I use `touchstart` event to trigger the action. I also need to use `event.stopPropagation()` and `event.preventDefault()` and then close manually the dropdown.

This is my code (I use Materialize with Meteor)
```coffeescript
Template.myTemplate.events
  'touchstart a.blue-text': (event,tpl) ->
     event.stopPropagation()
     event.preventDefault()
     # action code
     $('.dropdown-button').dropdown('close')
```

Hope this helps. Thank you!

**Comment by tdotholla** [comment]
I was actually having a problem until i implemented this commit: [1d94110](https://github.com/Dogfalo/materialize/commit/1d941102292f154fc2bd78eefb6fadf1f0649b2e) 

and then removed my own ` 'touchstart .selector': function() {...} map in meteor.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by adick** [comment]
Had the same issue. My fix is to replace the touchstart eventbindings with touchend. 

```
    else if (origin.hasClass('active')) {
        hideDropdown();
        $(document).unbind('click.'+ activates.attr('id') + ' touchend.' + activates.attr('id'));
    }
```
```
if (activates.hasClass('active')) {
	$(document).bind('click.' + activates.attr('id') + ' touchend.' + activates.attr('id'), function (e) {
		if (!activates.is(e.target) && !origin.is(e.target) && (!origin.find(e.target).length)) {
			hideDropdown();
			$(document).unbind('click.' + activates.attr('id') + ' touchend.' + activates.attr('id'));
		}
	});
}
```
