### ISSUE TITLE
Select without options shows undefined?

### ISSUE THREAD

**Issue by inventti-leonardo** [Dogfalo/materialize#2425]
:(

http://codepen.io/anon/pen/GoRBjG

**Comment by MetaiR** [comment]
i think its because of javascript and jquery
oommmm you know when you use select element in materializecss and put jquery code (      $('select').material_select();
)
it adds a ul and li elemnts to your select item which li of ul values is exactly value of your options element.
here the codes
http://codepen.io/MetaExploit/pen/vLYaRa
i think the mater is because u have no option element that it turn them to li and show there
actually its use the value of option which has "disabled selected" attribute for placeholder value and when u have no option the javascript or jquery (i dont know in this case which one do this) return undifined.
sorry for my bad english language its because its not my real language.
by the way congratulation you found a bug :D

**Comment by TyrionGraphiste** [comment]
Undefined is showing because no options exist. If you want to avoid this, add one disabled option.
