### ISSUE TITLE
Add function that reloads all components

### ISSUE THREAD

**Issue by carama-s** [Dogfalo/materialize#250]
I am making a website with dynamic content and if I dynamically add some components like inputs, buttons, ... it is impossible to reload the script except by adding a script tag with your script in src.

It could be great if you provide a function that recalls all your script to update the current HTML.

Thank you., I love your lib !

**Comment by hrishikeshs** [comment]
:+1:  on this feature request.  I too am in need of something like this, it would be cleaner for materialize to expose an api rather than everyone who is using this to implement their own method of doing so. If materialize can take care of this internally, it would be even better. Please see my comment on this pr  #327  as well. Thanks again for creating this!

**Comment by Dogfalo** [comment]
Possible fix, http://jsfiddle.net/rcMhq/

**Comment by hrishikeshs** [comment]
@Dogfalo Thanks! I found a neat way of handling situations like this within the framework I am using, basically, all I had to do was invoke the `Waves.displayEffect();` after making sure that my dynamically generated document fragments were in the dom. A nice use case for a JS mixin. :+1:

**Comment by Dogfalo** [comment]
I don't think that there needs to be one function that reloads all the components, that would just be bad for performance. When you're using dynamic templating systems like Angular or Spacebars in Meteor, you would want to only initialize what is necessary and you can do this by calling the init function again in a .rendered callback
