### ISSUE TITLE
icons not showing

### ISSUE THREAD

**Issue by replay111** [Dogfalo/materialize#2588]
I have just created project with gulp-sass, added Materialize with 'bower install materialize --save' and copied from bower_components/Materialize/font to <my_project>/src/font with directory structure.
During gulp serve I can't see that browser is loading anything with Material Icons - only roboto is loaded.
I did not change any of material scripts... why this is not working?

<img width="762" alt="zrzut ekranu 2016-01-03 o 19 17 05" src="https://cloud.githubusercontent.com/assets/5937475/12080047/a3a80aa8-b24e-11e5-9c66-3f474850b85f.png">

**Comment by Dogfalo** [comment]
See icon documentation

**Comment by replay111** [comment]
OK so what is the purpose of keeping those icons in project?
So if I want to use those icons offline I have to create font face for my own?

**Comment by acburst** [comment]
We are going to remove our icon fonts in a future release. This is because it is an unofficial icon font and needs constant fixing and updating to keep up to date with google's icons. The ones we use now in the documentation are google's official icons. You can read more about them [here](https://github.com/google/material-design-icons).
