### ISSUE TITLE
Select list not scrolling

### ISSUE THREAD

**Issue by neilhanvey** [Dogfalo/materialize#2592]
I have a select with a large number of items, it cuts off and will not scroll to these items using the scroll wheel. If i open the select and click the down arrow on the keyboard it scrolls ok. Any ideas on a fix? This is in all browsers

**Comment by acburst** [comment]
Can you post a codepen or something? It seems to be working for me locally

**Comment by dbnoble** [comment]
Is there a scroll bar visible? If not, set a `max-height` for the element as well as `overflow: auto` in your css.

**Comment by diegogurgel** [comment]
Hi @neilhanvey try call material_select() passing the select id
`$('#select-id').material_select();`

**Comment by Decadence** [comment]
I have this issue too. It's because select dropdown has max-height property.
This piece of styles helped me:

```css
.select-dropdown{
    overflow-y: auto !important;
}
```

**Comment by fega** [comment]
Please provide a way to reproduce it. like a [codepen](https://codepen.io/fega/pen/BWeZaG)

Closed due inactivity, feel free to reopen it if it is still necessary.

**Comment by apudiu** [comment]
Man, that problem really exists... You just cannot close due to inactivity, bear in mind this framework is not so popular that you will get huge traffic.

I'm also experiencing this issue, I've a form inside a bottom sheet modal & there's 5 dropdown's, (checkout the img), the first three dropdown shows scrollbar some times & sometimes not. & 2nd line has 2 scrollbar, those never shows scrollbars, sometimes it shows for a sec & then hides,

I'm filling `<option></option>` data using an (jquery) Ajax call. & as of documentation I'm destroying the previous elements & re calling the initiator.

So, we need fix, if you have more questions then pls feel free to ask,

THIS IS FIRST TIME I'M WORKING WITH THIS FRAMEWORK, & I DISCOVER THAT THIS FRAMEWORK IS FULL ....................... FULL............. OF BUGS. & REALLY SHOULD NOT BE CONSIDER AS OF NOW. THERE ARE SO MANY THINGS WHICH IS WRONG...


![image](https://user-images.githubusercontent.com/22303487/32495858-87fb8d1e-c3f1-11e7-8b75-08c7932e14cd.png)

![ssc](https://user-images.githubusercontent.com/22303487/32496262-d9420b98-c3f2-11e7-82c5-b9acd5fb243a.png)

**Comment by Ross-Rawlins** [comment]
Did you find a solution to this/

**Comment by bugy** [comment]
For those who are still facing the issue, try adding `backface-visibility: hidden` to the `.dropdown-content`.
For me the issue happened only in chrome, and according to multiple stackoverflow discussions, `backface-visibility: visible` works unreliably with different transformations in Chrome.

**Comment by xblue-light** [comment]
@bugy solution worked for me and whatever else I found in this thread and or the web final result that works for me:

**Comment by Souvik04** [comment]
How can I override the CSS class `dropdown-content` in ReactJS?

**Comment by pidugusundeep** [comment]
@xblue-light Thanks this helped.
