### ISSUE TITLE
Html range vs noSliderUi alignment flaw

### ISSUE THREAD

**Issue by SHAD0WF4X** [Dogfalo/materialize#2694]
Not sure whether it's a bug, but take a look yourself
![matbug](https://cloud.githubusercontent.com/assets/7324718/12522725/94e0f206-c152-11e5-9056-ce85ffd7810b.png)

**Comment by chifreaigle** [comment]
I dont get it :/

**Comment by SHAD0WF4X** [comment]
As you can see, the two sliders are not aligned equally.

**Comment by DanielRuf** [comment]
Can not reproduce it with the latest release.

**Comment by Robert-Held** [comment]
This is a thing for me, too. I can confirm SHAD0WF4X's issue.
The error even occurs on [the forms page](http://materializecss.com/forms.html), which I would assume to be the latest release. On local development I learned that the fewer steps you have on the range as a whole, the more obvious this misalignment becomes. (Example: a range that goes from 30 to 50 with steps of 10--meaning you have three steps on the whole range--has a bigger misalignment than the showcase range with 100 steps.)

Tested with FF 52.0.2 (32bit) and Chrome 56.0.2924.133 (64bit).

**Comment by DanielRuf** [comment]
When did you test? (Windows 10 64bit here)

![image](https://cloud.githubusercontent.com/assets/827205/24656051/1a5f714a-1941-11e7-8308-5e1767fffd17.png)

**Comment by DanielRuf** [comment]
Probably related to https://github.com/Dogfalo/materialize/issues/4464

**Comment by Robert-Held** [comment]
The moment I wrote my comment, on Win7 64bit.

Upon reading the reading the original post again, I see that I have misunderstood the issue here. Just saw the mispositioned blob and thought, that this is my issues, my bad.

Alignment of the range itself is fine. The big thumb is misaligned, though. 
![grafik](https://cloud.githubusercontent.com/assets/15276669/24673277/f8b775a6-1977-11e7-891d-181c9d5e6e2a.png)
Materialize's showcase

![grafik](https://cloud.githubusercontent.com/assets/15276669/24673434/a1ea0ef4-1978-11e7-8331-35a8f6dfcb02.png)
Lokal project

Maybe that's indeed a new issue... Sorry for mixing it up.

**Comment by DanielRuf** [comment]
The PR should fix this. https://github.com/Dogfalo/materialize/pull/4466/files

The PR is just in the master branch and not yet available as release.

https://github.com/Dogfalo/materialize/releases
>  **48 commits** to master since this release

**Comment by tomscholz** [comment]
Like @DanielRuf mentioned, should be fixed with #4466
