### ISSUE TITLE
Using Icons & Roboto font on Intranet

### ISSUE THREAD

**Issue by feldrim** [Dogfalo/materialize#2836]
I'm developing a project for intranet. So that Google Webfont dependency is not an option. I'm trying to host icons & roboto font on my own server. In [this page](https://google.github.io/material-design-icons/), it's explained how to do. It requires changes on materialize.css. Since it's a core issue, it would be better to include in the documentation for both CSS and SASS.

**Comment by Kail0** [comment]
I don't understand the problem here. 

If you don't want to host both icons and roboto font via Googles CDN you can download them here on Github [https://github.com/google/material-design-icons/tree/master/iconfont](Google Icons) & Google Font [https://github.com/google/roboto](Roboto).

Just make sure you change/delete all font-face option in materialize css / sass file.

**Comment by Dogfalo** [comment]
They have been
