### ISSUE TITLE
Button with icon got deformed while drawing for first time

### ISSUE THREAD

**Issue by aleksandrmaksimoviclt** [Dogfalo/materialize#2933]
Issue: when button WITH ICON got drawed for first time button got displayed like this:
| ______ICON_________SOME TEXT_____________|  
then when drawing()loading ends button is displayed as it should:
| _ ICON _ SOME TEXT_ |

**Comment by acburst** [comment]
Can you post some sample code?

**Comment by aleksandrmaksimoviclt** [comment]
`<body>
<div>
<a class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>button</a>
</div>
</body>`

Here is a sample code, all files from my issue are vanilla from materializecss.com

**Comment by aleksandrmaksimoviclt** [comment]
Same happens even on your website: [http://materializecss.com/buttons.html](url)

**Comment by fega** [comment]
@acburst @Dogfalo Yeah, this is a problem due delay in the download of the material design icons font, I guess that this spaces should have a defined size prior to the download

**Comment by tomscholz** [comment]
Use `<i class="material-icons">&#xE2BD;</i>` instead of `<i class="material-icons">cloud</i>`, if you want to avoid the "`ICON_________SOME TEXT_______|`". When using `&#xE2BD;`. This is what it looks like before the icon font is fully loaded
![bildschirmfoto 2017-07-21 um 21 56 57](https://user-images.githubusercontent.com/20381749/28480293-38489faa-6e60-11e7-877d-2a2d15ff9b2d.png)
