### ISSUE TITLE
meteor package and Sass

### ISSUE THREAD

**Issue by adrian-gierakowski** [Dogfalo/materialize#2948]
Hi

Does the meteor package include sass files? If not, is there a plant to support sass customisation in the meteor package?

thanks!

**Comment by SwarShah** [comment]
Use https://github.com/poetic/meteor-materialize-scss I have used this is in one of my meteor project.

**Comment by NitroBAY** [comment]
see #1018. Commit 5afb6000 add support. You may a little bit, tough, as there's not doc already and there's still issues as  #3281. Besides I needed to remove the materialize.scss otherwise when I added file per file (_variables.scss etc.) it was doubled with materialize.scss.
So yeah support is incoming maybe @Dogfalo could tell us a word about that ;)

**Comment by Dogfalo** [comment]
Deprecated issue, Sass has been added
