### ISSUE TITLE
Velocity JS transition

### ISSUE THREAD

**Issue by Plimsky** [Dogfalo/materialize#305]
I got this message in console 

> Velocity: First argument (callout.tada) was not a property map, a known action, or a registered redirect. Aborting.

With this code : 

```
$('.bg-image').velocity(
        "slideDown",
        {
            delay: 800,
            duration: 1500,
            complete: function () {
                $('#title-1').velocity("callout.tada");
            }
        });
```

So I can't use velocity transitions ?

**Comment by nathanhornby** [comment]
Thanks for this @Plimsky - I was having the same issue.

I wonder what @Dogfalo 's allusive issue with the syntax was, cause it looks fine to me!

**Comment by schwindy** [comment]
FYI to anyone seeing this, just dealt with this exact error. It was caused by a version mismatch between the original implementation and the new version I was trying to include (1.5.0).

1.2.2 works fine by including:
https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.min.js
https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.ui.min.js

Including these files solved my issue, at least. :D I'm assuming that something changed that broke it in the interim but it's possible that I was just failing to re-implement the new version properly.
