### ISSUE TITLE
can't scroll dropdown on touch devices (iOS and android)

### ISSUE THREAD

**Issue by neFAST** [Dogfalo/materialize#3085]
This issue can be replicated with the dropdown present on materialize demo page.
As soon as you touch the screen in order to scroll the content of the dropdown, it will close.

It seems a few issues have been reported with dropdown since the implementation of touchStart event, is there any official word on this?
Thanks

**Comment by cimtico** [comment]
I have just encountered this issue on my application, is there a work around?

**Comment by CraigH2013** [comment]
I have the same problem in my application.

![dropdown bug](https://cloud.githubusercontent.com/assets/3102109/18649363/2a1258a4-7e8d-11e6-99ca-6c5e16d66d51.gif)

**Comment by B-iggy** [comment]
Is there an official fix soon?

**Comment by garbit** [comment]
I'm still facing this issue as well. 

There seems to be a couple of proposed fixes (that currently don't seem to work).

```
.select-dropdown{
    overflow-y: auto !important;
}
```


A rewrite of the component - https://jsfiddle.net/c6buv1j8/11/ 

Fix seems to have been implemented but not pushed to the latest version - https://github.com/Dogfalo/materialize/issues/4200

**Comment by tdotholla** [comment]
I was actually having a problem until I implemented this commit: [1d94110](https://github.com/Dogfalo/materialize/commit/1d941102292f154fc2bd78eefb6fadf1f0649b2e)

and then removed my own ` 'touchstart .selector': function() {...} ` map in meteor; then all started working right again..

it happens because the touch event is happening multiple times (sometimes before the link is clicked and followed, and sometimes after) so the 2nd click makes the dropdown disappear.

**Comment by Dogfalo** [comment]
Fixed in v1-dev
