### ISSUE TITLE
Use of href to trigger modals, tabs etc. causes issue with SEO

### ISSUE THREAD

**Issue by abhishek9** [Dogfalo/materialize#3100]
In this framework href tag is used to trigger tabs etc. which contains id of target element like `href="#tab1"` and because anything starting with `#` in href is treated as a link to same page, search crawlers treat it as duplicate internal links to same page.

After migrating to materializecss from bootstrap I have seen that in webmasters google is now showing 5-6 internal links on every page, because i am using few dropdowns and modals trigger in header footer. 

To tackle this problem, bootstrap was using a nice approach to have something like `data-toggle="modal" data-target="#myModal"` So similarly for all elements like tabs etc. we can use `data-target` instead of href

Please look  into this issue, if any alternative could be provided instead of using href. This could become a messy problem for Search Engine Optimization.

**Comment by Dogfalo** [comment]
Then use a button
`<button data-target="modal1" class="btn">Modal</button>`

**Comment by WilfredoMa** [comment]
I'm sorry, I know this is old, but I think the answer provided by @Dogfalo is incomplete, because it only solves the problem for modals. 

I want to include materializecss tabs in my project, but find myself in the same situation in which I would prefer not to use href. 
In the official site ( [https://materializecss.com/tabs.html](url) ) there are no solutions for this when it comes to tabs, and the answer above does not work in this case, so could anyone tell me if its possible to avoid using href for tabs? I really think it should be, especially if its already possible for modals, but maybe I'm wrong.

Thanks!
