### ISSUE TITLE
Webpage CSS turns non-responsive when modal is open and we try to change zoom %

### ISSUE THREAD

**Issue by Dsupreme** [Dogfalo/materialize#3111]
When a modal is open and one tries to change the zoom % of the web page (Ctrl +, Ctrl -) the UI does not scale properly for the background webpage (modal scales properly).
Images:
Default (No Zoom)
http://prntscr.com/ayinq4, http://prntscr.com/ayio1d (modal open)
Zoomed in
http://prntscr.com/ayiobj (Modal opened after zooming in)
http://prntscr.com/ayiott (Modal opened before zooming in)

Link for reference: 
https://github.com/Dsupreme/Ang2
(I setup a basic project. I documented all the steps in setting up such a project. Please follow the readme.md in case any concerns.)

**Comment by J-tt** [comment]
## Description:

Elements stop being bound by page size when modal is active and the DOM size is changed (via zoom).

## Reproducible On
- Chrome (Version 61.0.3124.11 (Official Build) dev (64-bit))
- Edge (40.15063.0.0, EdgeHTML v15.15063)
- Firefox Nightly (55.0a1 (2017-06-10) (64-bit))

Codepen used to reproduce: https://codepen.io/J-tt/full/RgapBx/

----
The issue is relatively minor, as the elements will fix themselves when the modal is dismissed, but good work @Dsupreme! This one looked hard to find.

**Comment by Dogfalo** [comment]
The body width is no longer set while modal is opened in v1-dev
