### ISSUE TITLE
Forms do not work in card-content

### ISSUE THREAD

**Issue by jnguyen7410** [Dogfalo/materialize#3136]
Expected: Forms within cards should allow text edits and interaction
Actual: In 0.97.6, form input is blocked on cards

Was using a form inside of a card, when I realized that the input wasn't working. After investigating it, I narrowed down the problem to the version of Materialize. In 0.97.5, this was working fine. Switching to 0.97.6 broke this. 

Website not working [here](http://nguyeningcode.com/test/portfolio.html).
Website working [here](http://nguyeningcode.com/portfolio.html).

In the working version, all I did was switch the version number.

**Comment by acburst** [comment]
There are quite a few problems with your structure. The problem is only shown from the new version because there were some changes to the card-action class.

The main problem is that your form has a column class on it. Remove this and it should work. You should only use our column classes directly as a child of a row. Doing things like this will cause weird things to happen. In this case it made your form float: left without any clears.

**Comment by jnguyen7410** [comment]
Thanks for the advice. Will make the changes to fix the problem.
