### ISSUE TITLE
How can I use indicators on carousels?

### ISSUE THREAD

**Issue by Croghs** [Dogfalo/materialize#3315]
Hi, 
I really don't understand how I can use indicators... It works with full_width for me, but not with indicators ;( 

`$(document).ready(function(){
    $('.carousel').carousel({full_width: true});
    $('.carousel').carousel({indicators: true});
});`

and the html is just the example from the website (the last one)... But I added a height to see at least something.

Thx 
Croghs

**Comment by acburst** [comment]
Indicators for carousels are not in the current release. But I actually added some new features to carousel recently in 6ce0fdce0fc8229d84bc03f13f404a12601b600c.

This is currently in the public release but if you want to try it out you can download our latest master version. There may still be some bugs here and there because it's new so let me know if you get it working.
