### ISSUE TITLE
[SideNav/Meteor] Recent changes/Meteor update break sidenav

### ISSUE THREAD

**Issue by kcranky** [Dogfalo/materialize#3316]
After updating to meteor v1.3.4.1, the Hamburger on the sidenav is no longer visible. Clicking to the left of where the hamburger was flashes the sidenav once, but not again without page reload. 

This can be replicated by just creating a new meteor project and using the example given in the materialize docs. 

SideNav initialization is done on Template.onRendered.

`Template.sidenav.onRendered( function () {
    $('.button-collapse').sideNav();
});`

I have confirmed that is not tied to the meteor version by reverting back to the prior meteor version (1.3.3.1) where the component was working as expected. I also created a new project on Meteor v1.3.3.1, where the sidenav worked previously, and the issue persists.

**Comment by forgitit** [comment]
v0.97.6 removed old icons however the materialize docs for the sidebar hasn't been updated. 

Replace 

`<a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>`

with 

`<a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>`

In my case, since updating the sidebar is appearing (sliding-out) then disappearing while remaining in an open state as they overlay is visible and clicking away collapses the sidebar. It looks like the style rule '.slide-out' is calculating the transform wrong (transform: translateX(-100%)). Anybody else have this issue?

**Comment by kcranky** [comment]
Thanks @forgitit, this resolves the issue. 
@dogfalo Documentation needs update
