### ISSUE TITLE
Add X-Small size to grid

### ISSUE THREAD

**Issue by hamedmoody** [Dogfalo/materialize#3406]
Hi
how can i add X-Small size to grid such bootstrap?
Thanks

**Comment by mescuderocuu** [comment]
Hi, Bootstrap uses x-small grid because it uses different measure of what an small(768px and up), medium(992px and up) and large(1200px and up) devices are, while in Materialize are small(<600px), medium(between 600px and 992px) and large(>992px).
If you want to change this go to your materialize.css, there a some classes you need to change, for example in line 2800 start the media query classes, this helps to hide and show the content, to add your xsmall class you need to add
```
@media only screen and (max-width: 480px) { //you should change this number to what you consider X-Small size
  .hide-on-xsmall-only {
    display: none !important;
  }
}
@media only screen and (max-width: 480px) { //you should change this number to what you consider X-Small size
  .show-on-xsmall {
    display: block !important;
  }
}
```
If you still need help with this please let me know to help you out.
