### ISSUE TITLE
Is it possible to have 13 boxes in a single row?

### ISSUE THREAD

**Issue by Script47** [Dogfalo/materialize#3505]
Has anyone managed to fit 13 boxes in a single row in a responsive way? As you can see in the [image](https://gyazo.com/6c77b54e4cfca1f85e0f7d553703120a) the 13th box goes on a new line, is there any way to make it fit responsively on the single row?

Below is the code I'm currently using:

```html
<div class="row">
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1"></div>
    <div class="col s1">13</div>
</div>
 ```

CSS is not my forte hence I asked before messing with the core CSS.

**Comment by deepsheth** [comment]
Method 1: If you want them all to be equally wide, you should manually customize the CSS of `col s1` to have `width: 7.69` (100% / 13 columns). 

Having 13 columns all in one row is probably a bad idea if you want it to be responsive -- everything will look crammed on a phone. You should probably use `col s2 m1` so the columns are bigger when you shrink the screen size.

Method 2: And if you don't want to change the CSS directly, another alternative would be to divide the row into two large columns of size 12 and then divide those two large columns into 6 columns and 7 columns to get you 13, but of course the column sizes will not be equal.

So something like this below (notice the last two columns are size `col s1` instead of `col s2` in order to prevent exceeding 12.
```
<div class="row">
     <div class="col s12">
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
     </div>

     <div class="col s12">
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s2"></div>
          <div class="col s1"></div>
          <div class="col s1"></div>
     </div>    
</div>
```

**Comment by Script47** [comment]
@deepsheth thanks for the speedy response, I used the first method which helped a lot.
