### ISSUE TITLE
Range Finder Not Displaying values

### ISSUE THREAD

**Issue by pricetula** [Dogfalo/materialize#3543]
Following the documentation I still can not get the range slider to display the value. Using nouislider plugin
![materiali](https://cloud.githubusercontent.com/assets/3857337/17777144/11ca50dc-6568-11e6-9c0e-e18491b47665.png)
//Initialized 
var slider = document.getElementById('test5');
  noUiSlider.create(slider, {
   start: [20, 80],
   connect: true,
   step: 10,
   range: {
     'min': 0,
     'max': 100
   },
   format: wNumb({
     decimals: 0
   })
  });

//Imported all css files including nouislider plugin

<div id= ' test5 ' ></div>

**Comment by randyjensen** [comment]
You need to make sure you're using the Materialze noUiSlider CSS/JS since they have some extra goodness baked in. Here's a stripped down example of only what you need for the slider:

[http://codepen.io/anon/pen/VjNWOW?editors=1000](http://codepen.io/anon/pen/VjNWOW?editors=1000)

noUiSlider does have basic tooltip support as well if that's all you want:

[http://refreshless.com/nouislider/slider-options/#section-tooltips](http://refreshless.com/nouislider/slider-options/#section-tooltips)

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
