### ISSUE TITLE
label position incorrect when elemts not in own line.

### ISSUE THREAD

**Issue by Levitas** [Dogfalo/materialize#3551]
Hello.

if have the following source code

```
<div class="input-field"><input type="email" id="fos_user_registration_form_email" name="fos_user_registration_form[email]" required="required"><label for="fos_user_registration_form_email" class="">E-Mail-Adresse</label></div>
```

I get the following output: http://prntscr.com/c8acla

But if I manually change the source code (add enters in chrome developer tools) to

```
<div class="input-field">
<input type="email" id="fos_user_registration_form_email" name="fos_user_registration_form[email]" required="required">
<label for="fos_user_registration_form_email" class="">E-Mail-Adresse</label
</div>
```

So i just added line breaks manually I get the following output: http://prntscr.com/c8ad1t

The twig template files are UTF-8 without BOM and UNIX Row-end characters.

Any advice or is it a bug in the framework?

**Comment by kmmbvnr** [comment]
Are you on IE11?

**Comment by Levitas** [comment]
nope, chrome (as mentioned above)

**Comment by Nohinn** [comment]
Happened to me too.
I don't know why but in the latest relases a css left rule disappeared for the labels.

If you write:
`left: 0.75rem;`

As in older releases, you will have it placed correctly.
You should add this left rule to this part:
`.input-field label {`

**Comment by acburst** [comment]
Is there any code example that can reliably reproduce this bug?

**Comment by Nohinn** [comment]
Hello @acburst I have narrowed down the problem on my side.

On my project I use an HTML processor that removes unwanted whitespaces, etc. from the final HTML code. Causing the HTML of an input-field to be:
`<div class="input-field"><input type="text" id="txt1"/><label for="txt1">Label 1</label></div>`

Instead of:
`<div class="input-field">
    <input type="text" id="txt1"/>
    <label for="txt1">Label 1</label>
</div>`

On previous versions of the CSS having that `left: 0.75rem` fixed the position of the label. I see you have set on the latest commit a `left: 0`.

**Comment by acburst** [comment]
Yup I snuck it into another fix. Is everything working now?

**Comment by Levitas** [comment]
@Nohinn: Thats what I wrote in the first comment
@acburst: when i added the code mentioned by @Nohinn: it worked for me
