### ISSUE TITLE
[bug] sidemenu open/close issue

### ISSUE THREAD

**Issue by solute-niravsoni** [Dogfalo/materialize#3561]
i have 3 buttons that open/close same sidenav.
when i click on "button-1" it opens sideNav
then click on "button-2" it will close opened menu and open another menu
then click on "button-3" it will close opened menu and open another menu
then click on button-3 > button -2 > button-1 this time menu will not open
see example here:
http://codepen.io/niravsoni/pen/zBQWdb

**Comment by mescuderocuu** [comment]
The reason why that is happening is because when you open another sideNav the previous one is just hide, not close, once you click again the button it closes the sideNav, you can modify the materialize.js so it will always open or hide the buttons until the sideNav is close, if you still need the multiple buttons to open the same sideNav i can tell you how to modify the js file
