### ISSUE TITLE
Internet Explorer Switch not toggling

### ISSUE THREAD

**Issue by pbrocker** [Dogfalo/materialize#3599]
I am running material 0.97 and have both material.js and material.css installed. I have a switch toggle and it works wonderful in chrome, safari, and firefox. But it does not work in IE. I can click it and it focuses, but does not change the input to 'checked'. and does not change state.

**Comment by pbrocker** [comment]
solved. the issue was that i was generating a input via ruby (<% f.checkbox %>) and for some reason materialize was creating a extra input (or maybe ruby was). anyway fixed the issue by just rendering the input via html (<input>).

**Comment by adamwgriffin** [comment]
Rails generates the extra input when you use the checkbox helper method. The HTML specification says unchecked checkboxes are not successful, and thus web browsers do not send them to the server, so Rails generates the extra input to get around this.

Unfortunately when the extra hidden input is placed right next to the other checkbox input it causes the switch not to toggle in IE and Edge. If you still want to be able to get the unchecked value of the checkbox sent to the server all you need to do is move the second hidden input so that it's not next to the normal checkbox input. I put mine just outside the label tag that contains the input in the Materialize switch. Of course you need to render the input using html instead of using the helper method, like you mentioned.
