### ISSUE TITLE
Carousel doesn't work

### ISSUE THREAD

**Issue by larsvansche** [Dogfalo/materialize#3651]
The slider won't initialize at all. All the pictures are just displayed as plain pictures. The slider will get the class "initialized", but besides that nothing changes. Javascript tells me that the property "style" of undefined cannot be read. I also checked the materializecss javascript file near the problem, Google Chrome shows red lines under the "el" variable (which is probably the carousel element) in the inspector.

Does anyone know where this is coming from and how to fix it? 

I copied and pasted the code provided for the basic carousel at http://materializecss.com/carousel.html

**Comment by vishnu1991** [comment]
Hello @larsvansche ,
Its working fine.Looks like you may have missed a bit of js code or something.
You can try below **codepen**  or **download the zip** file.

[Codepen demo](https://codepen.io/vishnu1991/pen/pEbwAa)

[Carousel Demo.zip](https://github.com/Dogfalo/materialize/files/477368/Carousel.Demo.zip)

If you are still facing issue or your problem is not solved u can reply to this thread else you can close it.
