### ISSUE TITLE
Toggle one sideNav from multiple buttons

### ISSUE THREAD

**Issue by savtwo** [Dogfalo/materialize#3769]
I'm trying to toggle the sideNav from multiple buttons. It works the first time through for each button but then only the last button works on the first click. All the previous buttons require two clicks.

Steps to reproduce:
- Click "Button One" (sideNav opens)
- Click "Button Two" (sideNav opens)
- Click "Button Three" (sideNav opens)
- Click "Button One" (nothing)
- Click "Button One" (sideNav opens)
- Click "Button Two" (nothing)
- Click "Button Two" (sideNav opens)
- Click "Button Three" (sideNav opens)

Here's the [plunk](https://plnkr.co/edit/heFhKdg6z9iNiamzGwS4?p=preview).

**Comment by lsrock1** [comment]
New version in repository resolved this issue.
If you want to use multiple buttons in 97.7
I think you should modify some sidenav.js.
Under drag-target click listener, add sidenav overlay click trigger.

**Comment by savtwo** [comment]
Hey @lsrock1 thanks for the response. I am using v0.97.7. Not sure I follow so do you think you can provide an example of what the modification to sideNav.js would look like?

**Comment by lsrock1** [comment]
This problem is occured by var's scope.
When you open menu by click button, you can see some invisible drag-target eats half of browser.
If you click this to close menu, it calls removeMenu function that makes menuOut variable false.
However with multiple buttons it accesses only top of variable stack. so the last botton(here the third button) can only work properly.
To resolve this easily 
$('.drag-target').on('click', function(){
          removeMenu();
        })

->

$('.drag-target').on('click', function(){
         $('#sidenav-overlay').trigger('click');
          removeMenu();
        })

I think this is not a clear code, but it will solve your problem.

**Comment by fega** [comment]
Closed due inactivity, feel free to reopen it if it is still necessary.
