### ISSUE TITLE
Carousel - Misalign when switching slides too quickly

### ISSUE THREAD

**Issue by GLedoussal** [Dogfalo/materialize#3826]
Here is a codepen of the issue : https://codepen.io/anon/pen/jrokvv

**Comment by erchaves** [comment]
It would be great to get this fixed! It's a deal-breaker for me to be able to use it in a project. I tried to work on a quick solution using transitionend but it was too finicky and I don't have time at the moment to dig further.

**Comment by GLedoussal** [comment]
@erchaves I found a workaround to fix this, I won't make a pull request because I'm not really sure of my fix, there are maybe some side effects. Here is what you have to change:

```diff
@@ -7721,7 +7721,7 @@                                          
           if (n === undefined) {                              
             n = 1;                                            
           }                                                   
-          target = offset + dim * n;                          
+          target = (dim * Math.round(offset / dim) + dim) * n;
           if (offset !== target) {                            
             amplitude = target - offset;                      
             timestamp = Date.now();                           
@@ -7733,7 +7733,7 @@                                          
           if (n === undefined) {                              
             n = 1;                                            
           }                                                   
-          target = offset - dim * n;                          
+          target = (dim * Math.round(offset / dim) - dim) * n;
           if (offset !== target) {                            
             amplitude = target - offset;                      
             timestamp = Date.now();                           
```

**Comment by NitroBAY** [comment]
"I won't make a pull request"
I'm not concerned by this issue, but I am by the fact that people have no problem to take the code for free from an open source project like this but don't always want to help in return by making PR. @GLedoussal if you think about the great result you can have with Materialize without working on the plugin you could think that you could make a PR. It will maybe not be accepted but it will open a discussion with the team and other user about this and they will tell you if this is has side effect or no.
When one takes he should always give back.

**Comment by erchaves** [comment]
@GLedoussal, I think it's still helpful that you posted that idea even though you don't have time to fully test it and make a pull-request. We're all busy, it's cool. I also didn't go the extra step to make a pull-request because I'm not sure the best solution for this project. I ended up using [slick carousel](http://kenwheeler.github.io/slick/) instead which solves this issue by blocking a slide change until the previous slide change animation completes.

**Comment by NitroBAY** [comment]
@erchaves you have a weird conception of what open source has to be. Glad all dev are not like you so projects as Unix has been created.

**Comment by acburst** [comment]
@NitroBAY Its okay if he doesn't want to make a Pull Request. Sometimes I prefer a simple code snippet that suggests a fix instead of a Pull Request that isn't properly tested so that I can just write a fix myself. We do appreciate all the contributions we receive but by no means should you feel like it is mandatory. This issue itself is helping bring discussion and awareness to the bug.

**Comment by NitroBAY** [comment]
I'm also saying to PR because as you have +250PR and +1000 I didn't think that you had time to adapt the fix shown in issues in the code.
Anyway it's all good then.
