### ISSUE TITLE
openModal() -> modal('open') broken in 0.97.8

### ISSUE THREAD

**Issue by spflow** [Dogfalo/materialize#3850]
I was using openModal() in 0.97.7 and it was working great. Inadvertantly upgraded to 0.97.8 and it broke. I checked the documentation and it looks like the method was changed to 'modal('open')', but this syntax doesn't work either. By changing to the new syntax, I no longer get the "openModal is not a function" error, but nothing happens.

**Comment by Thanood** [comment]
It works here: http://codepen.io/anon/pen/ZBzYwB
(check the second button)

**Comment by zanozik** [comment]
Yep, was getting the same error, when I realized that they changed methods in a way, that `.modal('open')` not initializing as it was with `modalOpen()`, so you have to `.modal()` it first, apparently. The problem is, that they forgot to mention that in the [docs ](http://materializecss.com/modals.html)and only changed the syntax. Right now it's understood that it's only necessary to init modals to hook it to a trigger, like in the old version.

**Comment by spflow** [comment]
Thanks for the responses guys. @Thanood, yes that works. It's a little weird that you're/they're initializing the modal by selecting its class, and then opening it with its id. I guess maybe to initialize multiple modals at the same time? Yea, I totally missed the initialize concept in the Docs, though I must say it's a little cryptic.

**Comment by Thanood** [comment]
More like multiple triggers for the same modal.. :smiley: 

It's not needed to initialize by class, btw. Just any constructor that matches something. The `href` attribute on a link must be the same as the modal `id`. If you prefer buttons, you should be able to get away without using any IDs. IMO that's an improvement. :smiley:

**Comment by spflow** [comment]
Rgr, thanks!

**Comment by juandiego26** [comment]
@Thanood thanks, it's working for me
