### ISSUE TITLE
Documentation Error? (.modal is not a function error)

### ISSUE THREAD

**Issue by Romanulus** [Dogfalo/materialize#3862]
I'm attempting to call (in this case the console):

`$('#mymodal').modal('open')`
 
This fails, but when I try the following I get expected behaviour:
`$('#mymodal').openModal()`

The problem (I think) is that the documentation claims the .modal('open') method is the way to do it.
http://materializecss.com/modals.html

Does the documentation need updating?

**Comment by acburst** [comment]
In the latest release the modal plugin was changed. Make sure you are on the current release, if you are on older versions then use openModal

**Comment by alejogoez** [comment]
Materialize was be updated, also you have update the new version of the official page and ready

**Comment by jantivola** [comment]
Hi, the modal's not working when I incorporate it on yii2. I'm not sure what version of materializecss is this because the app came from the previous developer. 
![code](https://user-images.githubusercontent.com/10664192/29059942-4e73db12-7c4a-11e7-9607-15652fda6a37.png)
![console](https://user-images.githubusercontent.com/10664192/29059941-4e6cc368-7c4a-11e7-9410-9b62d919134f.png)

**Comment by calebebrim** [comment]
I'm on materialize:materialize@=0.97.6 and still have the same problem. 
I look for the code and I sow openModal function. 
Isn't supposed to have only "modal" function?
