### ISSUE TITLE
Is this possible to add a form field in menu drop down

### ISSUE THREAD

**Issue by naumanahmed19** [Dogfalo/materialize#3871]
I am trying to create advance search for which I want to add form element in search dropdown. But it seems not working . Any idea?

**Comment by kmmbvnr** [comment]
Can you describe what actually not working for you?

I see two problems - form closed on click, even on a text field, and the form labels inside dropdown makes overall content overflow a little.

To fix the first, you need to stop click even propogation for the form - `<form onclick="window.event.cancelBubble = true">`

And the second one could be fixed with a small piece of CSS:

```css
.dropdown-content .input-field.col  label {
  width: auto;
}
```

Here is the demo:

http://codepen.io/kmmbvnr/pen/gLbger

**Comment by ProProPro1** [comment]
Drop down dissapears when you click on form fields on mobile

**Comment by kmmbvnr** [comment]
@ProProPro1 yeh, propagation need to be stoped for the touch event as well

**Comment by kmmbvnr** [comment]
I'd updated the codepen with  `<form onclick="event.stopPropagation()" ontouchstart="event.stopPropagation()">`

**Comment by tomscholz** [comment]
Closed due inactivity
