### ISSUE TITLE
Select on('change') fires twice and one of the times with an empty value

### ISSUE THREAD

**Issue by jonasroessum** [Dogfalo/materialize#3886]
Code example: 

```javascript

$(() => {

    $('select').on('change', e => {

        const $this = $(e.currentTarget)

        console.log('value:', $this.val())

    })

})
```

When changing the select once, the following outputs in console:
```
value: test-value
value: 
```
The second time it fires, the value is simply not empty, which can break your script if you don't add the following checker:

```javascript
if ($this.val().length === 0) return 
```

**Comment by ekampp** [comment]
Do you have jQuery required twice? This has happened to me before if jQuery is included twice in your code base.

**Comment by jonasroessum** [comment]
No, only once:
```html
    <script src="../node_modules/jquery/dist/jquery.js"></script>
    <script src="../node_modules/materialize-css/dist/js/materialize.js"></script>
```

**Comment by ekampp** [comment]
Are you sure that nothing else has required jQuery on it's own? Other dependencies, which in them selves require the library will bind all events twice.

**Comment by jonasroessum** [comment]
Yes, the only thing that requires jquery in my project is materialize itself, which is odd, since you have to manually add it on your own.

**Comment by acburst** [comment]
Can't seem to reproduce this. Can you post your code? Maybe you added multiple listeners to the change event?

**Comment by developeranirudhprabhu** [comment]
@jonasroessum Try making following change and see if it helps

```
$(() => {

    $('select').off('change').on('change', e => {

        const $this = $(e.currentTarget)

        console.log('value:', $this.val())

    })

})
```

**Comment by Lyricalz** [comment]
I had this same exact issue and ended up here.

`if ($this.val().length === 0) return `

this solves it, but seems abit unnecessary.

**Comment by VeeK727** [comment]
I had this problem with my code
```
$('.myClassName').on('change', function(){
  console.log($(this).val());
});
```
which fired twice like the OP said. One with the value and other one empty. Reason that happens is because materialize creates a div that you actually interact with and hides the select element. The div has the same class so the onChange applies to the div as well. My solution was
```
$('select.myClassName').on('change', function(){
```
or you could use an ID, I haven't tested that.

**Comment by brunomarks7** [comment]
Try this:
`$('.select-wrapper.your_classe_name li').on('click', function(){
        console.log($(this).text())
});`

**Comment by Dogfalo** [comment]
As @VeeK727 said, you should only be applying the change event handler to the original select

**Comment by aneesshameed** [comment]
You got event fired twice because you have two dynamically created material select in your page, each time when you create material select you are calling $('select').on('change', e => {}) which is resulting events to be attached to material select. If you had three material select created then event would have fired thrice.
I prefer to remove all the prior events attached to material select and then attach a new event. 
$('select').off('change').on('change', e => {}) seems the clean way. I was using vue.js template repeater with mcss and came across same issue.

**Comment by malav-mavenvista** [comment]
9

**Comment by malav-mavenvista** [comment]
9

**Comment by theahmedy** [comment]
For those who may coming from a Livewire Laravel background and experiencing the same issue, it could be caused by @push @endpush because if you use the component multiple times on the same page, you end up with duplicated script, so the solution could be:

```
@once
    @push
     // your scripts 
     <script>
      .....
     </script>
    @endpush
@endonce
```

Refrence: https://stackoverflow.com/questions/38135455/how-to-have-one-time-push-in-laravel-blade
