### ISSUE TITLE
can't get <select> click event..but working after add class="browser-default"

### ISSUE THREAD

**Issue by tharakanwn2014** [Dogfalo/materialize#3909]
JS alert when click on <select> not working but it worked when added class="browser-default"..any solution for that..I need to get click event not change event.

**Comment by developeranirudhprabhu** [comment]
@tharakanwn2014 Can you explain in detail what you are exactly trying to do? If possible provide the code you are executing?

**Comment by SimHacker** [comment]
This is probably caused by the fact that selects often ignore user input, as described in this bug report I filed:
https://github.com/Dogfalo/materialize/issues/4098

Please re-open that bug report. It describes an input event tracking problem that causes select menus to ignore the item you select, if you don't click on it very quickly, or if you press down and drag. 

To demonstrate this, try popping up the menu by clicking (because pressing and dragging does not work, and starts a text selection gesture, which is another bug), then point at an item different than the currently selected item, then clicking very quickly. If you click quickly enough, it works. Then try clicking on another item than the one you just selected, but more slowly so you're holding the button or finger down for about half a second to a second. Notice that the menu pops down at the instant you press down on the button or touch the screen, but the onclick handler is never called. That is the bug I reported and fixed, but it was closed unfortunately because the developers don't see it as a bug. But it certainly is.

**Comment by Dogfalo** [comment]
This is not the same issue @SimHacker. This is due to the fact that the material select is not a <select> element. So you have to put the click handler on the select element that is created in JS or use an onchange event if that suits your needs better.
