### ISSUE TITLE
Uncaught TypeError: $(...).material_select is not a function

### ISSUE THREAD

**Issue by mingliang7** [Dogfalo/materialize#4167]
### Uncaught TypeError: $(...).material_select is not a function
Recently I've tried Materialize with Vue2 and Meteor. However, I got a problem where i can't initialize select 
``` 
$('select').material_select()
```
this is my code 
```
-HTML
        <div class="input-field">
            <select>
                <option value="test">Test</option>
            </select>
            <label for="">Materialize Select</label>
        </div>
-JS

export default {
   mounted(){
      $('select').material_select();
   }
}
```

thanks in advance!

**Comment by Dogfalo** [comment]
You have not included Materialize correctly in the project. Also please ask support questions on Stack Overflow.

**Comment by tahnik** [comment]
Any solution for this?

**Comment by DanielRuf** [comment]
@tahnik the function is definitely there so you ight have not included Materialze the right way.

https://github.com/Dogfalo/materialize/blob/master/js/forms.js#L477

Did you add the scripts to the bottom of your body after all actual markup?

**Comment by Craicerjack** [comment]
There seems to have been three different ways to do this based on the version of materialize you have installed. 

I had been using `1.0.0.alpha.2` in which   
`$('select').select();`
worked. 

I have since moved to the [latest release 1.0.0](https://github.com/Dogfalo/materialize/releases/tag/1.0.0) in which 
`$('select').formSelect();`

Check your version and then the appropriate method for calling it.

**Comment by vlagache** [comment]
I had the same problem with version 1.0.0

Solved with <script>M.AutoInit();</script> in the HTML code 
https://materializecss.com/auto-init.html
Hopefully this will help.
