### ISSUE TITLE
Can't seem to centre SOME divs correctly.

### ISSUE THREAD

**Issue by eddiethejibson** [Dogfalo/materialize#4205]
I'm trying to center all the divs on my page and it's proving to be a nightmare. I managed to center the main login form with the "m3-offset" class but it's not working for the rest of the cards, any ideas? Here it is: http://eddiej.pw/ feel free to f12. Code's here: http://pastebin.com/bBgaP073

**Comment by acburst** [comment]
You have to take into account the width of your content when centering.
So to center something with a 3 column offset, that means your content needs to be 6 columns wide because it would need 3 columns on each side adding up to 12 columns. 

Also if you are trying to center a fixed width, you don't need to use columns. You can use basic centering css like `margin: 0 auto`

**Comment by eddiethejibson** [comment]
@acburst Thanks for your response! I should just remove the whole column class and only use margin: 0 auto ? Is that all to make it responsive?

Thanks for all your help, if I can get this working I'll make sure to donate.

**Comment by acburst** [comment]
Well you are using 2 nested column classes. You should remove the inner one. And if you don't mind the size of the card being responsive then you don't need the margin, but if you want the card to be a fixed width, like you've set as 390px, then you should use the margin: 0 auto;
