### ISSUE TITLE
Double click on the modal button to open the modal window (code is dynamic)

### ISSUE THREAD

**Issue by ssmrkj** [Dogfalo/materialize#4330]
### Description
I came across to an issue, where I'm loading my modal dynamically (code spinets http://codepen.io/kjankauskas/pen/MpJXRy). When the DOM is loaded I have to double click the button to open the modal? Any idea why?

Use this Codepen to demonstrate your issue. http://codepen.io/kjankauskas/pen/MpJXRy

**Comment by acburst** [comment]
This is because you are only instantiating the modal on the first button click? If you want to instantiate at the time of the click, just trigger an additional click on the modal after you initialize it but really you shouldn't be initializing it on every button click. Ideally you would initialize it right after you append the elements and only do it once.
