### ISSUE TITLE
Roadmap question. Upgrading the architecture to Material Components

### ISSUE THREAD

**Issue by joeblew99** [Dogfalo/materialize#4334]
Can you comment on if you intend to upgrade to this ?

As i am sure your aware this is where all the new Material Design work is happening.
It supports i18n much better and has a better extensibility archi.

https://github.com/material-components/material-components-web

**Comment by Native-Coder** [comment]
Materialize is a front-end framework comprising mostly of CSS and a few jQuery extensions/plugins. Material Components: Web is a framework for Node.js They don't have anything to do with one another. You could use Materialize in node, but you couldn't use Material Components with, say, PHP. 

Additionally, Material-components is NOT "where all the new Material Design work is happening" Material Design is simply a [standard set by google](https://material.io/guidelines/). Materialize _implements_ this standard through CSS and jQuery, the the same way that Material Components _implements_ this standard through Node.js.

There a SEVERAL "Material Design Frameworks" to choose from.

- Materialize (The best due to it's ease of implementation and customizability, IMHO)
- [Material Design Lite](https://getmdl.io/)
- [Material UI](https://www.muicss.com/)
- [Material Components: Web](https://github.com/material-components/material-components-web)
- [Material Components: Android](https://github.com/material-components/material-components-android)
- [Material Components: IOS](https://github.com/material-components/material-components-ios)

ETC
Check out this [article](http://tutorialzine.com/2016/03/the-15-best-material-design-frameworks-and-libraries/) for a few more

So the short answer is "no".

**Comment by joeblew99** [comment]
Really ?
It IS where new Web Materials Design code is being developed.
i18n, RTL and all the improvments are happening in the repo i suggested.
Its not perfect yet, but it where thr train is heading.
Its also far easier to support becaue the lifecycle model is decoupled in their implementation so that any language can use it. Hence why they have React, Vue and other supporting libs.

Regarding the old Material Design repo...
The google team are only supported existing older the Materials Design lib so users dont get left in the dirt. They way all requests for new features are not getting taken up.
You can see from the git tree.

**Comment by thorncorona** [comment]
I'd prefer we leave MaterialCSS as is since it's already quite mature, and is widely used, meaning migration would be tough for any new features. There's really no reason to move to a more complex format when what we have already works.

**Comment by stap123** [comment]
@joeblew99 Isn't the mdc library going to end up being an alternate to this framework not a complimentary thing?

**Comment by Dogfalo** [comment]
Agree with @thorncorona here

**Comment by joeblew99** [comment]
Nope its going to replace it.
as i keep saying they are supporting the current Material Design repo
because you and others are dependent on it.
But going forward Material Components is where all the new functionality
lives.

If you dont believe me just look at it. Its obvious

**Comment by stap123** [comment]
@joeblew99 the mdc library is a framework library that is directly comparable to materializecss not complimentary. The Google team are working on creating a replacement for their Mdl library which they decided to bring to end of life. As you said above they are supporting the Mdl library because people have chosen to use it (Not us). Mdc is Google project that is being created so people can use it in their applications (not just web apps either). The material design spec isn't being recreated which is what materializecss uses.
