### ISSUE TITLE
Drop down popup not opened

### ISSUE THREAD

**Issue by gewisser** [Dogfalo/materialize#4384]
### Description
Drop down popup not opened
### Repro Steps
Click to selected region

![snap4](https://cloud.githubusercontent.com/assets/5417292/24254953/3d854b7c-0ff5-11e7-8c15-5043de472d58.png)

Use this Codepen to demonstrate your issue. http://codepen.io/anon/pen/zZjXVQ

**Comment by Dogfalo** [comment]
You need to initialize it as shown in the documentation

**Comment by gewisser** [comment]
Fixed. Try again. Does not work

http://codepen.io/anon/pen/zZjXVQ

**Comment by alexeiii** [comment]
I have the same issue. Dropdown doesn't pop up if there is no text in the element that activates dropdown. [Here](https://github.com/Dogfalo/materialize/commit/1d941102292f154fc2bd78eefb6fadf1f0649b2e) is the commit that introduced this isssue and some notes about possible problem.

@gewisser You can just remove `<span>` in your example. In my case it doesn't work since I have only icon without text.

**Comment by acburst** [comment]
Fixed in 42051a5

**Comment by vikaspotluri123** [comment]
I'm using the stable release (0.98.1) and have noticed the same thing. It works when the hover option is enabled, but otherwise it's iffy (worked once on mobile, but not later). I think something's funky with the click handler

**Comment by 19peaches** [comment]
Yeah it seems all navbar dropdowns are not functioning on click. I haven't checked the hoverable setting. Including on the Materialize website, the navbar example dropdown doesn't even work.

In dev tools it seems that the open status runs, but then is immediately closed again.
