### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by jirehstudios** [Dogfalo/materialize#4440]
Just went to view my site and the icons are not showing (just the name of the icons between the `<i>` tags). I also see the issue on the Materialize CSS official website.

[http://materializecss.com/icons.html](url)

**Comment by DanielRuf** [comment]
This is probably a mixed content issue on your website I can see the icons on http://materializecss.com/icons.html.

**Comment by jirehstudios** [comment]
@DanielRuf What does that mean? I cleared the cache and everything.

**Comment by DanielRuf** [comment]
When you click on your website with the right mouse button, select the `inspect` option in the popup menu. If you are on Chrome and Windows, press F12 or go to the settings - tools - developer tools.

Then you eill see the developer tools of your browser. Switch to the console tab there and reload the website. Do some error messages appear in the console? Are any 404 messages in the network tab of the developer tools?

We can not help you without the URL where this happens. This sounds like a wrong implementation on your side. Do you use `//:` instead of `http://` or `https://` in the URLs to the icons? Are the paths correct?

So far this issue is not reproducible and a typical misconfiguration in most cases. Please check the console in your browser.

**Comment by jirehstudios** [comment]
@DanielRuf I used `://` instead of `htts://` on the `<link>` tag and that did the trick, thanks!
