### ISSUE TITLE
Line next to active inputs.

### ISSUE THREAD

**Issue by SolarPolarMan** [Dogfalo/materialize#4443]
### Description
A small bar can be seen to the left of inputs

### Screenshots / Codepen
![Image of issue](http://i.imgur.com/DABYwv9.png)

[Codepen of issue](http://codepen.io/SolarPolarMan/pen/xqQRwW). For some reason on the codepen it can only be seen when zooming in.

**Comment by tomscholz** [comment]
🤔 When putting it inside a simple container the line disappears https://codepen.io/tomscholz/pen/yMQVaM

**Comment by SolarPolarMan** [comment]
It's the transform's fault :/ I guess I'll make a parent div.

**Comment by DanielRuf** [comment]
Or use the helper class `center-block`, flexbox or some other solution ;-)

http://codepen.io/anon/pen/mWQRxW

**Comment by DanielRuf** [comment]
The issue comes from the box-shadow

![image](https://cloud.githubusercontent.com/assets/827205/24478488/3fb2c254-14db-11e7-830d-0efd1696a082.png)

![image](https://cloud.githubusercontent.com/assets/827205/24478500/4c85c9c2-14db-11e7-9b12-2a58d008499a.png)

Setting a full width value seems to fix this
![image](https://cloud.githubusercontent.com/assets/827205/24478790/84440f80-14dc-11e7-9537-49cb0e4b5e3e.png)
![image](https://cloud.githubusercontent.com/assets/827205/24478844/cf1996b0-14dc-11e7-9dd6-7fdca3f7e6d3.png)


This issue here has to do with a rounding bug:

![image](https://cloud.githubusercontent.com/assets/827205/24478887/ff7e997c-14dc-11e7-9ae5-ec49dc1a8594.png)

![image](https://cloud.githubusercontent.com/assets/827205/24478894/0716c650-14dd-11e7-83c3-7080a4066247.png)

For me it seems to be a rendering issue in the Blink/Chromium/webkit engine, might be a well known issue. Not sure about this but there are many bugs related to CSS3 transforms.

**Comment by NonameSLdev** [comment]
This issue doesn't appear in Firefox:
![](https://gyazo.com/d0cc7720e2c4e57c1a32b2bb86013349.png)

**Comment by DanielRuf** [comment]
> This issue doesn't appear in Firefox:

Sure, this is not the same rendering engine ;-) This is an issue in webkit / Blink ;-)

**Comment by tomscholz** [comment]
Can we close this?
