### ISSUE TITLE
[Materialize][JQueryUI][select] dropdown does not close on click

### ISSUE THREAD

**Issue by aminnairi** [Dogfalo/materialize#4512]
### Description
Material select inside table does not close on click after JQuery UI script include and table body sorting with `$('#tableBody').sortable()`.

### Complete code reproduction
https://pastebin.com/AHdEa2M3

**Comment by jacobq** [comment]
Note that it appears to work OK when using jQuery 3.1.1 and removing jQuery UI (`.sortable()`)
See http://jsbin.com/yigadu/3

**Comment by DanielRuf** [comment]
Mixing jQuery UI and Material Design components feels a bit wrong.

**Comment by aminnairi** [comment]
Why not?

I simply need the Material Design from @Dogfalo and the JQuery's sortable component in my table so that I can do cool things and my users are not forced to go back to Microsoft's Excel, creating their document and then sending it to my app.  And maybe using others cool component I discovered from JQuery UI.

I still believe that one day we could do all that in a breeze with Web component like Google are doing it with Drive.

So for now, I used the fallback `.browser-default` but I hope I could use the Materialize design in a near future for the eye candy effect!

**Comment by jacobq** [comment]
@aminnairi While the idea of being able to easily integrate things is great, the problem is that when there is overlap of functionality between tools they can conflict with each other. For example, both may assume exclusive control over click events received by some element in the DOM. 

If you really want to use them together, go ahead, but when you encounter problems like this you'll have to dig in with the dev tools and see why they aren't working together in this case. I suspect that the `sortable` is removing / recreating elements in the DOM without removing and reinitializing materialize's event handlers.

**Comment by bassie1995** [comment]
You could use a table plugin specifically geared towards just this: data tables.
For Materialize, I use dataTables and the Materialize 'plug-in' that someone made, and it works pretty well.

**Comment by gideonso** [comment]
@bassie1995 

Can you point us to the plug-in??

**Comment by bassie1995** [comment]
Discussion is here: https://datatables.net/forums/discussion/26569/feature-request-materialize-css.
Specific comment: https://datatables.net/forums/discussion/comment/88540/#Comment_88540.

**Comment by tomscholz** [comment]
Closed due inactivity. Feel free to reopen it, if it's still necessary.

**Comment by sh4rk60800** [comment]
I have fixed it:
http://jsbin.com/tagadoloza/3/edit?html,output
