### ISSUE TITLE
Transifex needs better maintaining

### ISSUE THREAD

**Issue by NonameSLdev** [Dogfalo/materialize#4734]
Our transifex isn't maintained at all. I tried to help by offering translate the docs to Hebrew. That was two months ago. I also had to push and send more and more messages. And over two months, Alvin (who's the only one who's in charge of the materialize transifex) didn't respond. It needs more maintainers that can easily add people into the editing teams and the new languages needed into the project so the people added can actually edit.
I'm not the only one suffering from this: https://github.com/Dogfalo/materialize/issues/4654

**Comment by tomscholz** [comment]
I personally think we don't need translations at all. I don't know a single web framework that actually supports officially translations and I think this is for a reason. In my opinion is English a must. If you're not able to speak English and try to become a developer you are literally fucked. On the other hand it is cool and practical, but if @Dogfalo is not able to maintain it we should discontinue the service

**Comment by Dogfalo** [comment]
I add new languages when there is enough contributor demand so that the entire translation does not depend on just one person. In any case I accepted your request for a Hebrew translation since you are so motivated, in addition I made you a coordinator for the language so you can invite people who you think will help with the translation effort for the language.
