### ISSUE TITLE
Materialize docs should be seperated from materialize library

### ISSUE THREAD

**Issue by NonameSLdev** [Dogfalo/materialize#4735]
I've always wondered why these are in the same project?
Combining the docs with the actual project is messy, and results issues and PRs about the docs and about the actual project in the same place, which is unclean. Why not create a materialize-docs project and do all the docs work there? It could be much easier, cleaner and more welcoming to new users who have no idea what they're going into. It's also bad practice IMO.
What do you think?

**Comment by tomscholz** [comment]
It's definitely **not** practice. Almost every js/css project I now has the docs in the repo, but everytime in a seperate folder called docs/ . Creating a new repo would be a bad idea, because then we would have to maintain two repos and I guess I speak for all maintainers when I say, that I don't want that.

**Comment by tomscholz** [comment]
whoops there was a word missing

**Comment by DanielRuf** [comment]
I agree with @tomscholz.
