### ISSUE TITLE
Side Navigator not fixed on small devices

### ISSUE THREAD

**Issue by alexisdiel** [Dogfalo/materialize#4814]
On small devices, when i open the side navigation and open a collapse menu that overflows the height, I can make small move on X-axis, 

I found an inline-style on `ul.side-nav` element.
`overflow: auto;`

But not found when/where it's applied, i thing that's applied from some external JS.

I resolved the problem changing the inline-property from `overflow: auto` to `overflow-y: auto` 

![image](https://user-images.githubusercontent.com/7047656/27135904-258dc3b4-50f0-11e7-8575-51d7cfb8c68b.png)

**Comment by DanielRuf** [comment]
The inline style is from the sidenav component https://github.com/Dogfalo/materialize/blob/master/js/sideNav.js

**Comment by DanielRuf** [comment]
Seems we need a fix like https://github.com/Dogfalo/materialize/commit/d9d0028e55d5477d66761fe53231e8750c22b5ba.

**Comment by DanielRuf** [comment]
I guess you mean overflow and not override.

**Comment by alexisdiel** [comment]
See my pull request, i've fixed changing the css override on nav-mobile initialize

**Comment by acburst** [comment]
Changing the overflow might just be a bandaid fix. If the layout is done correctly then you shouldn't be able to scroll horizontally. This might mean there is some css error that is causing some element to have extra width giving the sidenav horizontal scrollability.

I think its a good principle to try first to really diagnose the problem before proposing a fix that may just be fixing the symptoms instead of the root cause.

**Comment by DanielRuf** [comment]
@alexisdiel it is just in the docs as far as I can see it.
