### ISSUE TITLE
Modal is responsive but background (when modal is activated) is not

### ISSUE THREAD

**Issue by yammadev** [Dogfalo/materialize#4898]
### Description
Apparently modal is responsive but background (when modal is activated) is not. I tested it using the modal declaration inside header, footer, body and main tags, with no positive results. Any idea of how to solve this? 

Thanks! 👍 

### Repro Steps
1. Open modal
![Imgur](http://i.imgur.com/SFKYEcs.png)

2. Resize the window. The modal is responsive, but the background is not.
![Imgur](http://i.imgur.com/JaPERFl.png)

3. Close modal, and background resizes to full width. 
![Imgur](http://i.imgur.com/jg11HUC.png)

**Comment by andikahmadr7** [comment]
It's because when u open the `modal` or click the modal trigger, idk somewhere in `js` file tell the `body` element to has a fixed `width` as your current browser width. But when I deleted the width from inspect element, everything is fine as u want. now im tryin to find where is the code.

**Comment by yammadev** [comment]
@andikahmadr7 I was reading about this, and as you say, the modal's width is controlled by the js, could be better a css solution for this?

**Comment by Leafino** [comment]
I'm fairly sure this is to maintain the body position since the scrollbar is hidden. It isn't aesthetically pleasing I agree. Perhaps a better option would be to use the calc() CSS function. They could get the page width with the scrollbar... remove the scrollbar and get the width then subtract them from one another and put that as the css value of calc(100% - scrollbar_width).

**Comment by yammadev** [comment]
@Leafino Could you do a pull request or something?

**Comment by acburst** [comment]
Fixed with modal rewrite
