### ISSUE TITLE
net::ERR_FILE_NOT_FOUND materialize.js

### ISSUE THREAD

**Issue by tatva-nisarg** [Dogfalo/materialize#4912]
I got following error in my console log with Aurelia framework 

```
Error: (SystemJS) XHR error loading file:///D:/Projects/wamp/www/resultsoftware/ui/jspm_packages/github/Dogfalo/materialize@0.99.0.js
Error: XHR error loading file:///D:/Projects/wamp/www/resultsoftware/ui/jspm_packages/github/Dogfalo/materialize@0.99.0.js
Error loading file:///D:/Projects/wamp/www/resultsoftware/ui/jspm_packages/github/Dogfalo/materialize@0.99.0.js as "materialize" from file:///D:/Projects/wamp/www/resultsoftware/ui/src/main.js
```

**Comment by tomscholz** [comment]
Please open an issue over at the aurelia-materialize-bridge repo
cc @Thanood

**Comment by tatva-nisarg** [comment]
I think so issue with this repo @tomscholz

**Comment by tomscholz** [comment]
Ok. Can you than explain a little bit further what your problem is? Just a console log isn't very informative. How are you using materialize? cdn, npm, bower, meteor?
### Expected Behavior
Tell us what should happen...

### Current Behavior
Tell us what happens instead of the expected behavior...

### Steps to Reproduce
Include code to reproduce, if relevant
