### ISSUE TITLE
Pushpin strange scrolling behavior

### ISSUE THREAD

**Issue by mjbain10** [Dogfalo/materialize#4926]
### Description
I am trying to have a pushpinned navbar, but have some issues with the page content jumping suddenly once the navbar reaches the pinned top position.

I want to know what is the correct way to have a page with content, and the pushpin navbar.

### Repro Steps

- Started with [initial codepen for pushpin demo, unchanged.](https://codepen.io/kmmbvnr/pen/XNXVaY)
- Add text or other content to the #sass div (or any other of the colored divs)
- Scroll slowly past the point where the navbar becomes pinned. You will then see the weird scrolling behavior. It's easier to catch if you click and drag the scrollbar slowly.
- [See this edited codepen with the issue](https://codepen.io/anon/pen/XgEBwg)

I'm probably structuring the HTML incorrectly or something, as this issue also appears exactly with my other projects. I'd appreciate any help, thank you!

**Comment by acburst** [comment]
The content is jumping in both examples. Its just that when you add text, the jump is noticeable whereas you don't notice it in the initial codepen because its all one solid color. In order to not have a jump when using pushpin is to wrap the element that becomes fixed in a container with a set height equal to the height of the element. When an element becomes fixed, its removed from the flow of the document making all the elements below it jump upwards. 

https://codepen.io/anon/pen/GExzRq

**Comment by mjbain10** [comment]
Thank you! That did the trick
