### ISSUE TITLE
Active tab indicator isn't displayed if tab panel was initially hidden

### ISSUE THREAD

**Issue by flipp5b** [Dogfalo/materialize#4929]
Suppose, we have a tab panel that is placed inside a container with `display: none`. The tab panel is initialized with `$('ul.tabs').tabs();`. Then we change container style to `display: block`.

## Expected Behavior
It's expected for me that active tab should be marked with indicator.

## Current Behavior
But it's not. The indicator appears only when we click on any tab or resize browser window.

## Possible Solution
It looks like indicator is intentionally initialized with nonzero width only when tab panel is visible ([here](https://github.com/Dogfalo/materialize/blob/master/js/tabs.js#L98)). I suppose it's required for something, but the result looks counterintuitive for me.

## Environment
* Version used: 0.99.0
* Codepen: https://codepen.io/anon/pen/EXLxxV

**Comment by doubleOrt** [comment]
Yes, i also faced this issue, there are 2 solutions: 

1- Create a callback for the showing of the container of the tabs (the element that is hidden), and in that callback, re-initialize the tabs.
2- Disable Materialize's standard tab indicator manually in your CSS, and then edit the .tab.active class so that it has a border-bottom that replaces the tab indicator, if you go this way, you will lose Materialize's nice tab changing animation, but if you try a bit hard you should be able to replicate it. Or you just create another simple animation like i did (a combination of scaling and skewing on active, it looks great).

**Comment by tomscholz** [comment]
https://github.com/Dogfalo/materialize/issues/4837
