### ISSUE TITLE
CSS Bug - card-image mobile

### ISSUE THREAD

**Issue by MiniSquash** [Dogfalo/materialize#4973]
Text also gets bugged if i set the max-height: none

**Comment by tomscholz** [comment]
Provide a codepen and fill out the [issue template](https://github.com/Dogfalo/materialize/blob/master/.github/ISSUE_TEMPLATE.md)!

**Comment by Maqsyo** [comment]
https://codepen.io/MaqsYo/pen/rwbMGY

The affecting class is following:
```
.card.small .card-image, .card.medium .card-image, .card.large .card-image {
  max-height: 60%;
}
```

He's using materialize v0.99.0

**The Problem is following:**
If he's using a card-image, the image gets cut in mobile view.
You can see this issue here: http://imgur.com/l7ozz2X

**Comment by MiniSquash** [comment]
https://codepen.io/MaqsYo/pen/rwbMGY?editors=1100

Expected behaviour : 
1) Image gets seen regarding or all device sizes. Right now on smaller device some part of the image is hidden.
2) If i add style="max-height: none" the image appears regardless of all device size without part of the image is hidden. However the text beneath it will get resized and appear out of the box. (Hard to explain this one)

**Comment by acburst** [comment]
For fixed height elements, it is very hard to make sure nothing is cut off at any size. Because you have added the constrained height class of large, the image will be cut off. We set the max height of the image to 60% and the max height of the text to 40%. You can tweek these numbers yourself but I do not know of a way that can guarantee an image will always be showing regardless of the image's size. You can try playing around with background image cover, but that just tries to center the image and will sometimes cut the image off as well.

**Comment by MiniSquash** [comment]
Alright. Thanks for the help
