### ISSUE TITLE
SideNav not removed to the left

### ISSUE THREAD

**Issue by ottomen** [Dogfalo/materialize#498]
I changed the width ot the sidenav from 240 to 305 pixels, but when it closes, the part of sidenav stays vislble, because script is adding -250 pixels to the left. 

Issue:
http://prntscr.com/5v5idq

How i should fix this bug?

**Comment by ttemiel** [comment]
From your screenshot I gather you are using the sass version.
In that case I think the best way to solve this problem would be to change the value of $sidenav-width (now at the top of sass/components/_sideNav.scss) instead of changing the width manually. The offset is defined as -1 * ($sidenav-width + 10), so then the sidebar would be completely out of view.

**Comment by ottomen** [comment]
Yep, i'm using the SASS version, and i'm already changed $sidenav-width value, but when sidanav is closing, the backwards offset to left is added by javascript (as you see in the screenshot). I thought the offset value is defined in the javascript, did it?

**Comment by ttemiel** [comment]
Oh, sorry, my bad. You're right, it seems the menu-width is also hardcoded into the javascript. A workaround would be to change that value (var menuWidth) manually in the js. There should be an easier way, though.

**Comment by ttemiel** [comment]
A somewhat more general solution would be to change the definition of menuWidth to:

    var menuWidth = - parseInt($(menu_id).css(options.edge)) - 10;

This should play nicely with the default setup, and changing the sass-variable. I've added it to my pull request #561

**Comment by ottomen** [comment]
Thanks!

**Comment by ttemiel** [comment]
On second thought, it occurred to me that this doesn't play nicely with a changing viewport width. For example: if the sideNav is in view on rendering the page, but hidden afterwards because of a smaller viewport, this workaround doesn't work. So it is probably better to accept menuWidth as an option in the initializer.

I've prepared a new pull request that implements this: #570

**Comment by ottomen** [comment]
Also i found a -240px value, manually added in the materialize.js file: http://prntscr.com/601wvg . I replaced it with the menuWidth variable.

**Comment by acburst** [comment]
We've finally added the menuWidth in as a jQuery plugin option.

Added in 87d6f560c1706f343410dfd2bdb041a1901ac831
