### ISSUE TITLE
Cannot update to 0.100.1

### ISSUE THREAD

**Issue by JanZ1503** [Dogfalo/materialize#5010]
## Expected Behavior
Update to 0.100.1 should work properly

## Current Behavior

Receiving following bug when trying to update:
meteor update materialize:materialize
=> Errors while upgrading packages:           
                                              
While checking for materialize:materialize@0.100.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

## Your Environment
Using following OS 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Using Meteor 1.4.4.2

**Comment by fligen** [comment]
I am having the same issue using mint os 18

**Comment by csellis** [comment]
I'm having the same problem. Any idea what's causing it?

**Comment by Altroo** [comment]
I can't download it also from the materialize website in google chrome, 

![capture d ecran 2017-07-25 a 14 25 38](https://user-images.githubusercontent.com/30314254/28574221-373dd8d6-7145-11e7-9749-6e6954597ec3.png)

**Comment by udacitystudents** [comment]
I have the same problem 👎

**Comment by trajano** [comment]
I have the same problem on Windows 10

**Comment by asiftyro** [comment]
Same issue here OSX 10.12.4 

Last version I can use  - <code>meteor add materialize:materialize@=0.100.0</code>

> meteor add materialize:materialize
> > meteor add materialize:materialize
>  => Errors while adding packages:             
>                                               
> While checking for materialize:materialize@0.100.1:
> error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by tomscholz** [comment]
1. It makes no sense if everyone writes: "I have the same problem". Just upvote the actual issue. :)2
2. We are working on that

**Comment by asiftyro** [comment]
@tomscholz yes sire ;)

**Comment by kartboy16** [comment]
fourseven:scss@4.5.4 was causing this problem for me.  I downgraded to 3.11.0 and materialize could install again.

**Comment by Dogfalo** [comment]
> Since meteor 1.4.1+ (fourseven:scss 3.9.0+), we do not have prebuild binaries anymore. You are required to set up the required toolchain yourselves.

You may have to build the binary yourself. Give that a try and see if it works.
https://github.com/fourseven/meteor-scss#compatibility

**Comment by kartboy16** [comment]
@Dogfalo K, wish me luck.

**Comment by kartboy16** [comment]
@Dogfalo Never done this before so please excuse  my stupidity...  

Trying to build with `node-gyp` and it's asking for a binding.gyp file.  `node-gyp` shows a basic binding.gyp file but have you created one before for materialize?  Anything I need to include?

Basic structure of binding.gyp:

```
{ 
  "targets": [ 
    { 
      "target_name": "binding", 
      "sources": [ "src/binding.cc" ]
    }
  ]
}
```

**Comment by Dogfalo** [comment]
https://guide.meteor.com/1.4-migration.html
Try this

**Comment by kartboy16** [comment]
Following the [guide](https://guide.meteor.com/1.4-migration.html) above and `node-gyp`, I updated command line tools `xcode-select --install` and made sure i'm on `python` 2.7.   Since i'm trying to get the atmosphere package working, I `git clone https://github.com/Dogfalo/materialize.git` and then published it to atmosphere as `kartboy16:materialize`.  I then `meteor add kartboy16:materialize` to build and bring it in to my project.  

Ran my project and got this error:

![developer_tools_-_http___localhost_3000_](https://user-images.githubusercontent.com/4443907/28898871-f536930c-779c-11e7-8a0f-fd53aab79f4d.png)

**Comment by JanZ1503** [comment]
@Dogfalo Why are binary builds no longer provided? I did not update meteor or anything, the only part I tried to update was materialize to 0.100.1 from 0.99. I always ran my meteor on 1.4.4.2, so binaries at least for version 0.99 existed for meteor 1.4.4.2, but maybe I misunderstood your point.

This seems to be a blocker to many people, also as there seems a lack of documentation how to install the latest version now.

I think the overall expectation for any meteor user is that `meteor add materialize:materialize` works, or that clear documentation is provided how to install it.

**Comment by kartboy16** [comment]
@JanZ1503 Am I missing something?  Looking at package.js file, it says `api.use('fourseven:scss@4.5.4'); `

**Comment by JanZ1503** [comment]
Ah, I see - scss comes with materialize - I did not see it in my packages list, but now I understand what you meant.

Yea, it looks like in materialize@0.99 fourseven:scss@3.10 was used and the latest materialize version now requires 4.5.4, which does not come with pre-built binaries anymore, which breaks the standard `meteor add materialize:materialize`

But interestingly, scss says that their 3.9 version already has no pre-built binaries, however materialize 0.99 with scss 3.10 could be installed without building the binaries manually. @Dogfalo , do you happen to know why?

**Comment by seabrus** [comment]
@JanZ1503 @kartboy16 @Dogfalo
Hi,

Here are results of some my tests. Hope they could help us.

A). `meteor remove materialize:materialize`
B). Then I add `materialize:materialize` as a local package:

![selection_001](https://user-images.githubusercontent.com/10603559/28930387-7a48cf54-787b-11e7-8fad-191d9322b590.png)

All files in the directory `packages/materialize` are taken from the `materialize:materialize` distribution ZIP file. 
To understand that this is a local package, just change a line in the `package.js` file:
```javascript
Package.describe({
  name: 'materialize:materialize',  // http://atmospherejs.com/materialize/materialize
  summary: 'Materialize - LOCAL VERSION',
  version: '0.100.1',
  git: 'https://github.com/Dogfalo/materialize.git'
});
...
```
 
C). To make sure that everything is clean, I remove the `node_modules` directory and make `meteor reset`
D). Add packages: 
`meteor add fourseven:scss`
`meteor add materialize:materialize`
`meteor npm install`
`meteor run`

At that stage I had my app ready to work. But the system informs that it can't find the package `materialize:materialize` and in the console I see:
```javascript
Packages['materialize:materialize']
undefined
```

OK, I check the code in the `materialize.js` file and then replace `window.Materialize.` with `Materialize.` -- such assignments are used in the new part of code (`Modal` function). Note: there is a period at the end of `window.Materialize.` because I change only those places where properties of the object `window.Materialize` are modified, and not the `window.Materialize` is introduced.

After these changes Meteor can takes it correctly and my app starts working. 

***Conclusions***
1). It looks like there are some problems in the Atmosphere package for the version `0.100.1`.
2). To work correctly with Meteor the `materialize.js` should be fixed a little to export a correct `Materialize` object.

**Comment by kartboy16** [comment]
@seabrus Awesome detective work!!!  

Since Meteor's moving away from Atmosphere anyway, I decided to go down the NPM route instead.    

```
meteor npm install materialize-css@0.100.1 --save
meteor npm install hammerjs --save
```

created client/stylesheets/style.scss and added: 
`
@import '{}/node_modules/materialize-css/sass/materialize.scss'; `

In my main.jsx:
```

import _Hammer from "hammerjs"
import "/node_modules/materialize-css/dist/js/materialize";
```

```
// made global
Hammer = _Hammer;
Materialize = window.Materialize;
```

Copied fonts and placed them in `/public/fonts/roboto`

WORKS!!!

**Comment by jfhenon** [comment]
@kartboy16 Followed religiously your instructions and it works indeed! 
I also believe NPM is the right way to go.

**Comment by afifsohaili** [comment]
@kartboy16 i'm wondering what version of `fourseven:scss` are you using? Mine seems to report ```
   While processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: File to import:
   {}/node_modules/materialize-css/sass/materialize.scss not found in file:
   /Users/afifsohaili/Projects/sports-arena/{}/client/main.scss
```

**Comment by kartboy16** [comment]
`fourseven:scss@4.5.4`

Double check the location of materialize.scss in your node_modules.

**Comment by tomscholz** [comment]
1. It is easier to use the npm package instead of the atmosphere package.
2. [Here](https://github.com/tomscholz/materialize-meteor-sass-demo) you can find a little demo repo, that shows how that could look like.

>  Those fourseven:scss issues should be discussed in their repo, not here.

I agree with @JanZ1503. Any discussion around `fourseven:scss`should take place at their repo. Not ours.

**Comment by anubhav756** [comment]
`meteor add materialize:materialize@=0.100.0` works

**Comment by bmcgonag** [comment]
@jfhenon  and @kartboy16 I'm trying to emulate your suggested changes, and I used the repo created by jfhenon, but my styles (after removing materialize:materialize from .meteor/packages) are not being respected at all.  

Any thoughts on what I might be doing improperly, or other hints for using npm?

**Comment by kartboy16** [comment]
@bmcgonag Any errors?

**Comment by bmcgonag** [comment]
@kartboy16 No sir.  Just doesn't render any of the pages using Materialize styling. 

I'm using Meteor 1.5.0.  

I have added materialize to the <head> section for now, but would really prefer to be able to use it through NPM so others can easily get it setup when the pull the repo.  I hate to see atmosphere going away, it was a lot easier to just get things working from my end.

**Comment by tomscholz** [comment]
@bmcgonag Can you share code or do you have a public repo?

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bmcgonag** [comment]
I can't share that repo as it's for my work, but let me modify one of my other repos that's on github, and I'll post a link.  Might take me the night to get to it.

**Comment by cunneen** [comment]
I've just published an atmosphere package [appworkshop:materialize@0.100.1-appworkshop](https://atmospherejs.com/appworkshop/materialize) , having forked the official materialize package and then made the ( [changes suggested](https://github.com/Dogfalo/materialize/issues/5010#issuecomment-320016257) ) by @seabrus .

It's working nicely for me. YMMV.

**Comment by bmcgonag** [comment]
@cunneen I just set it up and it's working.  I didn't install fourseven:scss first, so initially it completely locked up my terminal, and left meteor running as a process, but after a quick reboot I added the fourseven:scss@4.5.4 to my packages, ran meteor, then ran your package, and it's working.  It did warn me, however about experimental versions.

**Comment by cunneen** [comment]
@bmcgonag That's great it's working for you, thanks for letting me know. Yes the experimental version warning is deliberate; it's because I versioned my package with a hyphenation at the end (0.100.1-appworkshop). People should use the official package if (or when) it works for them.

**Comment by Dogfalo** [comment]
We're releasing a bug fix update (v.0.100.2) with the changes suggested by @seabrus and updating the meteor instructions to 
```
meteor add fourseven:scss
meteor add materialize:materialize
```
