### ISSUE TITLE
How can we slide text without using Carousel?

### ISSUE THREAD

**Issue by vipin733** [Dogfalo/materialize#5166]
Hey I'm using particlesjs for background effect now. problem is I want. move my text without changing background effect. first I thought to use  Carousel but problem with Carousel is its take space but I do not want 
here is code  https://jsfiddle.net/j6h059b4/
in this i want slider1 and and slider 2

**Comment by K-YSoftware** [comment]
itu harusnya di pisah pake row nah udah gitu di buat kelas baru biar kepisah gitu,saya pake bahasa jawa

**Comment by Grezvany13** [comment]
@vipin733 if you simply add the ParticleJS div inside the .carousel (without making it a .carousel-item), it will remain there without sliding.

example: https://jsfiddle.net/fdaopg2t/

The only down-side is that the interactive effects of ParticleJS won't work, since there will be a div on top of it (which blocks any mouseOver events).

**Comment by acburst** [comment]
Seems resolved
