### ISSUE TITLE
[1.0.0-alpha.1] Dropdown in navbar not working

### ISSUE THREAD

**Issue by Lolincolc** [Dogfalo/materialize#5349]
## Expected Behavior

The Dropdown menu should open on hover or on clic.

## Current Behavior

Dropdown menu in navbar doesn't work, when hover or on clic, nothing happen.

## Steps to Reproduce (for bugs)

This bug can be seen in the documentation : http://next.materializecss.com/navbar.html#navbar-dropdown

## Your Environment

* Version used: 1.0 Alpha
* Browser Name and version: Chrome V.63
* Operating System and version (desktop or mobile): Windows 10

**Comment by jacobq** [comment]
I think this is happening because of two things:
1. Documentation says attribute name is `data-activates` but code uses `data-target`
2. Initialization appears to no longer be automatic (e.g. may need to call  `$(".dropdown-button").dropdown();`)

Here is a [working CodePen](https://codepen.io/jacobq_/pen/JOJMoJ) based on the example on the docs site with these two modifications.

**Comment by acburst** [comment]
Fixed in b17de31. We'll update the live docs later today

**Comment by Lolincolc** [comment]
@jacobq  Yes, it works now, thank you for your help!
@acburst Nice, thank you for all your hard work :)
