### ISSUE TITLE
select dropdown makes modal scroll

### ISSUE THREAD

**Issue by ray007** [Dogfalo/materialize#5473]
I have a form with a `<select>` tag inside a modal dialog.
Clicking on the select makes the modal scroll, since the options-dropdown doesn't fit inside the modal.
The dropdown would need to be outside in its own layer to avoid this.

**Comment by kirthick** [comment]
style="overflow:hidden"

**Comment by ray007** [comment]
And how should that help when the dropdown is too large?

**Comment by bab2683** [comment]
you can solve this in 2 ways:
- apply overflow-y:inherit instead of auto to the .modal class
- apply position:relative to the .dropdown-content class

in the first case the select field will go out of the modal and the modal will have the same height
in the second case the modal will go to its max height and the will be scrollable but visually looks better than leaving it as is. 

I had the same problem

**Comment by kirthick** [comment]
overflow hidden in parent element

**Comment by kirthick** [comment]
and position absolute

**Comment by bab2683** [comment]
do you mind showing some code as where to put those styles?

**Comment by ray007** [comment]
none of this makes things really better

**Comment by ray007** [comment]
Is there a reason for the `dropdown` to not be a `collection` in a `modal`?

I'd be willing to make a PR for that...

**Comment by acburst** [comment]
Container option added in 42aa7476.

You can specify `document.body` as the container of the dropdown to pull the dropdown out of the modal.
