### ISSUE TITLE
[DatePicker] value of input is not respected in Picker UI

### ISSUE THREAD

**Issue by vuhrmeister** [Dogfalo/materialize#5557]
## Expected Behavior
In `options` I set a different format (`format: 'dd.mm.yyyy'`).
If I then prefill the input value with e.g. `01.01.2018` this date should be selected in the UI.

## Current Behavior
Unfortunately the value is displayed in the input field, but no date is selected in the UI.  
However, if the input is empty, the date of today is selected properly.

## Steps to Reproduce (for bugs)
```html
<input type="text" class="js-datepicker" value="2018-01-01" />

<script>
  const options = { format: 'dd.mm.yyyy' }
  const $elem = document.querySelector('.js-datepicker')
  const instance = M.Datepicker.init($elem, options)
</script>
```

## Your Environment
* Version used: 1.0.0-alpha.3
* Browser Name and version: Chrome 63
* MacOS, Desktop

**Comment by Dogfalo** [comment]
Use the `defaultDate` option

**Comment by ray007** [comment]
Does that mean we need to evaluate the `value` attribute of the `input` tag ourselves and set `defaultDate` in the options if we want things to work smoothly?

**Comment by MrKrypto** [comment]
I think you need to reopen this because the behaviour changes depending on the formatting. Also, I can't find a workaround using defaultDate...

# Formatting
materialize-src-v1.0.0-beta
Verified in IE11, Chrome and Edge

Initialize input using jquery, but have also tried without straight to DOM instance - same result:

`$('.datepicker').datepicker({ format: 'dd/mm/yyyy' });`

## Test1
format = dd/mm/yyyy
input value = 15/05/2017

### Result:
Picker opens set to 5th Mar 2018.
Selecting Ok sets the input value to 05/03/2018

So here it seems to ignore the format and treat the date as mm/dd/yyyy.

## Test2
format = dd mm yyyy
input value = 15 05 2017

### Result
Picker opens with current date indicated, but not selected (date is different font but not highlighted).
Selecting Ok sets the value of the input to empty.



### Other notes
I can't work out how to set a dd/mm/yyyy formatted value using defaultDate either. The only thing I've found that works is:

`instance.setDate(new Date("2017-05-15"));`

...but as the date is in a different format (yyyy-mm-dd) it means you have to parse the input value.

This can't be right? Ray - did you find a solution?
