### ISSUE TITLE
v1.0.0-beta : Maximum call stack size exceeded with Modal

### ISSUE THREAD

**Issue by RyushinShendo** [Dogfalo/materialize#5828]
## Expected Behavior
I have a bottom sheet modal who open a classic modal for confirmation message.
In fact, I do my stuff in my bottom sheet modal, and I valid with a modal-trigger button. A modal with a summary opens for confirmation, without closing the bottom modal (normal).

## Current Behavior
In Google Chrome (Version 65.0.3325.181), I have this error on the console log
![image](https://user-images.githubusercontent.com/38457150/38858879-1f2ba4bc-422d-11e8-962c-f57d0f453728.png)

No problem with Firefox.

## Possible Solution
Not really a solution, but I've try this : 
1. Close my bottom sheet modal before my confirmation modal opens.
2. Add 300ms of timeout and open my classic modal.
3. No error.

## Steps to Reproduce (for bugs)
I have reproduce this issue here : 
https://codepen.io/anon/pen/OZLXvQ

1. Click on button "Modal" to open bottom sheet modal.
2. Click on button "Modal" inside bottom sheet modal to open a classic modal.
3. Show error on console log.

## Your Environment

* Version used: Materializecss v1.0.0-beta
* Browser Name and version: Google Chrome (Version 65.0.3325.181)

Thanks guys !

**Comment by laxell** [comment]
I have came across the same issue. Seems to be a problem with nested modals in general (not only the combination of bottom sheet modal and normal modal demonstrated here). If you close and open the second modal you can make the whole browser crash (the error message is triggered and looped to infinity...).

**Comment by Mzeus** [comment]
I noticed a similar error while using a datepicker inside a modal with body as container on v1.0.0-beta with chrome. If you open de datepicker inside de modal, and then reopen de first modal, it start generating this error with no stop:

![bug](https://user-images.githubusercontent.com/17267907/39050458-5b3fa56c-449d-11e8-8d49-dae967af7644.png)

I didnt created a codepen because if you dont kill the window quickly the memory used by chrome keep growing and can cause your computer to run out of memory.

This is the code that I used on v1.0.2-apha to make datepickers work on modals:

```javascript
	$('.datepicker').datepicker({
		container: 'body'
	});
```

To prevent this to happend while having container body on datepicker you use container null (set as default) or comment the line that force the modal to focus on line 3003:

```javascript
      key: "_handleFocus",
      value: function _handleFocus(e) {
        if (!this.el.contains(e.target)) {
          //this.el.focus();
        }
      }
```

I dont see a use of container body on datepicker anymore, because they work well on modals on v1.0.0-beta, but this error can block chrome completily and its important to get fixed.

**Comment by Dogfalo** [comment]
Looking into the issue now.

**Comment by Dogfalo** [comment]
So this should still be fixed by 3ea4667aeb65e7f5edda170c05e09c79ea854026. Since datepicker relies on Modal, this is the same issue and will fixed upon next release.

**Comment by mwinner313** [comment]
for me when i already has a opened modal and a button in it triggers another modal , this thing happens.
this means that i can't have two opened modal at the same time.

**Comment by mwinner313** [comment]
what i alreay endup is to close the open one and after a couple of time (like one sec) trigger the secend and the error is gone

**Comment by eduardoalvara2** [comment]
Is happening to me the samen error that @mwinner313, even if y close the first modal and open the second one very fast, the error of "Maximum call stack size exceeded" appear. If I do the same thing again, it starts to stack it self without stoping

**Comment by jamesallan93** [comment]
I had this problem, i fixed it by using setTimeout to open other modal while the main is closing, 300ms did the trick.
