### ISSUE TITLE
select box border is not visible 

### ISSUE THREAD

**Issue by mdrahiem** [Dogfalo/materialize#5911]
select box border is not visible when I am zooming the window.

https://codepen.io/anon/pen/wjmKMe

![image](https://user-images.githubusercontent.com/12086760/39859673-2d4dd0dc-5458-11e8-9720-0e6150b2ead6.png)

**Comment by alexwbaumann** [comment]
The provided CodePen was not initializing the select even though I see it in your screenshot. See updated [CodePen](https://codepen.io/anon/pen/vjapoZ). Issue doesn't seem to be happening for me in Chrome 66.0.3359.170. Are you able to provide additional details about your issue so that it can be reproduced?
