### ISSUE TITLE
Support for readonly attribute on components

### ISSUE THREAD

**Issue by YakupIpek** [Dogfalo/materialize#6081]
Checkbox and select elements are ignoring readonly attribute despite they support disabled attribute. I am sure other components has same issue as well. 

Can you please support readonly attributes for input components ?

**Comment by zaeval** [comment]
When you do ```FormData()``` with JavaScript, the disable property field does not include a value? I think there should be a read-only attribute because of this problem.

**Comment by zaeval** [comment]
![image](https://user-images.githubusercontent.com/8649474/61506752-1fc11880-aa1e-11e9-8dc7-2bfc53052993.png)
I've solved it, but there's a problem.

![image](https://user-images.githubusercontent.com/8649474/61506812-55fe9800-aa1e-11e9-9149-538bd9cf71e6.png)

![image](https://user-images.githubusercontent.com/8649474/61506889-965e1600-aa1e-11e9-9caf-a7f7a332d50b.png)

As shown above, readonly is an error that occurs because focus is possible unlike disable.

We need to modify the js file to solve this. However, because html5 made readonly possible to focus and impossible to modify, we must create a different state unless you prevent focus like disable.

**Comment by zaeval** [comment]
I think it's better not to focus like disable.
