### ISSUE TITLE
Chips-Element initialised with empty array does not reflect changes in that array

### ISSUE THREAD

**Issue by szauner** [Dogfalo/materialize#6317]
## Expected Behavior
When giving an empty array to a Chips element via options in the initialisation like
`var tags= [];`
`M.Chips.init(chipsElement, {data: tags});`
I would expect that array to contain chips that will be entered in the element.

## Current Behavior
Currently changes to the Chips-element will only be reflected in the given array if the array already contained elements before.

## Steps to Reproduce (for bugs)
Here is a codepen with to Chips-elements that demonstrate the difference in behaviour:
https://codepen.io/F3nc3r/pen/YgmGWK

1. Enter a new chip, e.g. 'tag3', in the first Chips-element and chlick the Button 'Do it for 1'. The div below the Chips-Element will then contain 'tag1,tag2,tag3'.
2. Ender new chips in the second Chips-element, e.g. 'tag1' and 'tag2' and then click the Button 'Do it for 2'. The div below the second Chips-element will not contain anything, because the array did not get changed.

## Your Environment
Tested on Firefox 66 in Windows 10.
MaterializeCSS-version 1.0.0 found here: https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css

**Comment by acburst** [comment]
The original arrays should not be how you check the data in the chips. It is working for the first example only because it has nested objects and therefore javascript is using an alias. 

To properly access the array, you can access the chipsData property on the Chips component.

here's an updated codepen: https://codepen.io/anon/pen/XQQgzb
