### ISSUE TITLE
Native <select> does not work when only using CSS

### ISSUE THREAD

**Issue by lanthier** [Dogfalo/materialize#6458]
When I only pull in the CSS library, all of my `<select>` elements become hidden, likely because I didn't initialize them via JS.

## Expected Behavior
When I pull in the library, I expected my `<select>` element not to change at all, because [this documentation](https://materializecss.com/select.html) says that it's a jQuery plugin.

## Current Behavior
Pulling in the CSS library will seemingly hide all `<select>` components.

## Possible Solution
Move the `<select>` CSS out of the CSS library. If we're exposing the CSS separately from the JS, they should not be dependent on eachother.
Another option is to at the very least document that utilizing the standalone CSS will break all `<select>` elements.

## Steps to Reproduce (for bugs)
1. Utilize the CSS library, doesn't matter if it's the .min or the CDN.
2. Try using a <select> anywhere where that CSS is scoped to, it will not appear visible.
[Codepen here](https://codepen.io/Lanthier/pen/BaaaOyG)

## Context
I only really needed a library for some good CSS styles so my project didn't look terrible.

## Your Environment
I was using the 1.0.0 release in a TypeScript vue.js site, chrome/firefox both the same behavior
* Version used: 1.0.0

**Comment by doughballs** [comment]
I’m not sure this is a genuine issue.

There are two ways to use Materialize. The basic usage is by including the standard compiled css and js, and this covers every component.

The second way is using a custom build, via sass for css and by the grunt for js. You can choose which components to use for your project.

If I understand you correctly, you want to include the default css (which covers all elements including selects) but you do not want to initialize the component via js, which leaves the selects unusable.

Materialize is a modular framework, each component has its own sass and js file, and you can’t have one without the other.

**Comment by lanthier** [comment]
Oh, my bad! I didn't realize I would need to include both in order to use this! I totally thought I could easily just utilize all of the CSS. Well fair enough, I will say it's kind of problematic that I would need to manually initialize a component every time I create one. There are a lot of beautiful looking designs this framework can create, but I think this kind of kills it for me. Nonetheless, I'll close the issue. Thanks for the fast reply!

**Comment by doughballs** [comment]
You can always include the compiled css and js, and init all components with one line of code.

Why is it such a problem to include the js? And why don’t you want to use the Materialize styled selects? I’m struggling to think of a use case where you would want the styling but not the functionality. JS makes the web work...?

**Comment by dohliam** [comment]
@doughballs For what it's worth, this bug / feature breaks the drop-down menu [here](https://dohliam.github.io/dropin-minimal-css/), and from reading the discussion above it sounds like Materialize will probably have to be removed from the [list of "minimal" frameworks](https://github.com/dohliam/dropin-minimal-css) if it can't be included on its own without JS. As @lanthier said, Materialize CSS is beautiful in every other respect (and I've enjoyed using it to create things like [PDFs from Markdown documents](https://github.com/dohliam/workflow)), so this is unfortunate, but I understand if using the CSS independently doesn't fit with your design goals for the project.

**Comment by pwcreative** [comment]
@lanthier Did you read the docs page about selects?

https://materializecss.com/select.html

Adding a class of broswer-default fixes your issue removes the need for JS. Pen below.

https://codepen.io/doughballs/pen/rNNVodV

@dohliam

Materialize doesn't claim to be a CSS only framework, I don't think? It has many cool JS components that are (I imagine) a big attraction for people (and which would be impossible/impractical via CSS alone).

That said, there are many ways to strip out all but the necessary javascript, and many components can be used without JS at all. As shown above, the included browser-default class name generates a traditional select without the need for javascript.

The question is why Javascript dependency would be a deal breaker seeing as the web literally runs on it.

**Comment by pwcreative** [comment]
Just had a quick look in the docs as to exactly how much of Materialize is functional without javascript. Turns out most of it. (Obviously anything that involves complex interactions requires javascript.)

**No JS required:**

1. Badges
2. Buttons
3. Breadcrumbs
4. Cards
5. Collections
6. Footer
7. Icons
8. Navbar
9. Pagination
10. Preloader
11. Color
12. Grid
13. Helpers
14. Media
15. Pulse
16. Shadow
17. Table
18. Transitions
19. Typography
20. Checkboxes
21. Radio Buttons
22. Range
23. Select
24. Switches
25. Text Inputs

**JS required**

1. Carousel
2. Collapsible
3. Dropdown
4. FeatureDiscovery
5. Modals
6. Parallax
7. Pushpin
8. Scrollspy
9. Sidenav
10. Tabs
11. Toasts
12. Tooltips
13. Waves
14. Autocomplete
15. Chips
16. Datepicker

**Comment by dohliam** [comment]
> Materialize doesn't claim to be a CSS only framework, I don't think?

@pwcreative Absolutely -- didn't mean to imply otherwise. However, @doughballs mentioned they were "struggling to think of a use case where you would want the styling but not the functionality", so I thought I'd give an example to show that there are indeed cases where people might want to use the styling without including the JS.

In any event, for our use case this issue was resolved by simply editing the css and removing the `display:none` property. This seems to work fine so far since we aren't using the CDN. Also, as you said, most of Materialize is functional without javascript, so I think it's reasonable to keep it on the "minimal" list for now. :smile:
