### ISSUE TITLE
Mobile select not working correctly on new iOS

### ISSUE THREAD

**Issue by pwcreative** [Dogfalo/materialize#6464]
**Expected Behaviour**

The tapped option should select.

**Current Behaviour**

The tapped option is not selected. The option before or after is being selected.

**Steps to Reproduce (for bugs)**

Visit https://materializecss.com/select.html on mobile and try the first example.

**Context**

This issue has been brought up several times in the Gitter feed, and I've noticed it on my own sites. Obviously a user not being able to select their intended option has pretty huge ramifications for UX.

**Your Environment**

iPhone Xr
iOS 13.1

**Evidence**

You can see from the video that the selected option flashed grey first, and the the incorrect option is displayed.

https://youtu.be/8Udc8R6yqwU

**Comment by Maverick0809** [comment]
https://github.com/Dogfalo/materialize/commit/c0da34049deec36efbd4681f73b3446e92918ca8 fixes this Select function, but NOT the Navbar dropdown-content options on iOS 13.1.2

Any ideas?

**Comment by joshualyon** [comment]
@Maverick0809 as a workaround for Dropdown, I've added an empty touchend event handler to the Dropdown.

In looking through the dropdown history, I noticed a `touchend` event on the document was added to fix an issue where the dropdown was getting left open in some cases. If I removed the `touchend` event, the dropdown closed most of the time except for when a slight scrolling motion occurred when clicking on an item (which aligned with the commit history notes on what this and the related `isTouchMoving` was attempting to fix). But when the `touchend` event was left in tact on the body, the click event didn't occur on the dropdown item. 

This made me suspect it could be a potential event bubbling / propogation issue, so I did a bit of searching and in one of the documents I found they mentioned something about a Safari oddity around bubbling events wherein an event would only be bubbled up if:

> 1. The target element of the event is a link or a form field.
> 1. The target element, or any of its ancestors up to but not including the <body>, has an explicit event handler set for any of the mouse events. This event handler may be an empty function.
> 1. The target element, or any of its ancestors up to and including the document has a cursor: pointer CSS declarations.

Which made me wonder if something was going on with the event not bubbling up because only the body had the `touchend` event and the dropdown itself didn't. The document also mentioned that the registered event handler could be anything, even an empty handler, so I gave it a shot and it seems to have resolved the issue on iOS 13 for me. 

Here's the rough additions

```
constructor(el, options){
   ...
   this._makeDropdownFocusable();
   this._resetFilterQueryBound = this._resetFilterQuery.bind(this);
   this._handleDocumentClickBound = this._handleDocumentClick.bind(this);
   this._handleDocumentTouchmoveBound = this._handleDocumentTouchmove.bind(this);
   this._handleDropdownClickBound = this._handleDropdownClick.bind(this);
   this._handleDropdownKeydownBound = this._handleDropdownKeydown.bind(this);
   this._handleTriggerKeydownBound = this._handleTriggerKeydown.bind(this);
   this._emptyFunctionBound = () => {}; // <<< added an empty handler next to the other definitions
   this._setupEventHandlers();
   ...
}

_setupEventHandlers(){
   ...
   // Item click handler
   this.dropdownEl.addEventListener('click', this._handleDropdownClickBound);
   this.dropdownEl.addEventListener('touchend', this._emptyFunctionBound); // <<< added this
   ...
}
_removeEventHandlers(){
   ...
   this.dropdownEl.removeEventListener('click', this._handleDropdownClickBound);
   this.dropdownEl.removeEventListener('touchend', this._emptyFunctionBound); // <<< and removed it too
   ...

```

**Comment by assistcontrol** [comment]
I think what we're seeing here is the standard Materialize pattern:

Users: [submit over 500 bug reports]
@Dogfalo: `Patreon update`
Users: Materialize no longer works on iOS
@Dogfalo: `Patreon update`

It's really disappointing.

**Comment by pwcreative** [comment]
@assistcontrol 
It would be nice to get quicker resolution but personally I just find workarounds in the meantime.

**Comment by JimboM4CK** [comment]
@pwcreative Have you found a workaround for this issue?

**Comment by doughballs** [comment]
@JimboM4CK 

Materialize comes with it's own workaround built in:

adding

`.browser-default`

to any materialize form input does exactly what you'd expect it to.

**Comment by JimboM4CK** [comment]
Thank you @doughballs for the very helpful workaround of suggesting not to use materialize select at all. /s

An alternate approach I've found to work was to include the patched select.js file after including the materialize.js file. 

The patched select.js can be found here: [select.js](https://github.com/Dogfalo/materialize/blob/v1-dev/js/select.js)

**Comment by doughballs** [comment]
@JimboM4CK 

You’re so right - pointing out how to keep a select functioning using a single class name from the published documentation is so unhelpful, I don’t know that I was thinking 🤦🏻‍♂️

**Comment by kiere** [comment]
I think the writing is on the wall, unfortunately.  I keep coming back to this framework only to be let down again-and-again.  This iOS 13 bug is a MAJOR problem and the maintainers should have made fixing a bug that affects such a huge user base a priority.  Factor this in with the open CVEs that they don't want to address and I've come to the conclusion it's time to move off Materialize and onto something that's more likely to keep being maintained.

I think it's healthy for maintainers to take a break, but it's also critical to fix security issues and bugs when they arise.  Committing to something and sticking with it for all those people that depend on it for their applications is a big deal.  Dropping off the grid and barely responding to issues like the iOS 13 dropdown/select issue is a deal-breaker for me.  It's embarrassing our company and it makes it look like **we** aren't addressing bugs.  This issue is affecting every iOS mobile device that's been updated and I have to do something yesterday.

With traction like Materialize has, the maintainers should have brought on some additional maintainers _before_ taking a break.  This would allow maintenance to continue until they were ready to come back.

**Comment by pwcreative** [comment]
@kiere while I half agree with you (and feel your pain), I do feel like problem solving is our job and in the absence of a new release (for all the reasons that may be behind that) there are fixes above that work - enqueuing the patched select.js after materialise.js as suggested by @JimboM4CK fixes the issue. Everybody has different needs - for me, despite these drawbacks Materialize is still my go to and will be for the foreseeable.

Marking as fixed thanks to @JimboM4CK

**Comment by Maverick0809** [comment]
@pwcreative , like said before, enqueuing the patched select.js after materialise.js does fix the select issue but NOT the navbar dropdown issue.

**Comment by pwcreative** [comment]
@Maverick0809 my issue was specifically about select inputs on mobile, as per the the title, and so has been correctly closed. The dev's are aware of it and it has been fixed in a patch. Although I realise you deserve thanks for alerting initially!

Although select.js uses dropdown.js, they are independent of each other so it is no surprise that this patch does not fix the issue with dropdown.js.

**Comment by kiere** [comment]
@pwcreative My project uses webpack and I have not been able to get this patch working that way.  Are you using webpack or something like it?

**Comment by pwcreative** [comment]
@kiere no sorry, I don't use Webpack. We use Wordprsss and the way I got it to work was by enqueuing materialize.js, then enqueuing select.js, then enqueuing my custom.js. So serving 3 separate JS files.

What I haven't tried yet is adding the patched select as it's own component at the time of compiling my materialize.js using grunt - I did try replacing select.js with the patched version, but this did not work! So adding it as it's own component (select2.js) could technically work...

**Comment by lKapaM6a** [comment]
This is all due to the animation, I just prescribed **.dropdown-content** one style **transform: none;** and everything worked on ios, although the animation will stop working;)

**Comment by lkusam** [comment]
> Thank you @doughballs for the very helpful workaround of suggesting not to use materialize select at all. /s
> 
> An alternate approach I've found to work was to include the patched select.js file after including the materialize.js file.
> 
> The patched select.js can be found here: [select.js](https://github.com/Dogfalo/materialize/blob/v1-dev/js/select.js)

Thank you. it worked

**Comment by Siddharth-Ashri** [comment]
> > Thank you @doughballs for the very helpful workaround of suggesting not to use materialize select at all. /s
> > An alternate approach I've found to work was to include the patched select.js file after including the materialize.js file.
> > The patched select.js can be found here: [select.js](https://github.com/Dogfalo/materialize/blob/v1-dev/js/select.js)
> 
> Thank you. it worked

How exactly did you do that? Did you include the file in the materialize-css folder in node_modules?

**Comment by lkusam** [comment]
@Siddharth-Ashri  I put the select file in my project folder and added script tag to the file after i load material.js in html page. 

You place the select file anywhere you want and reference it properly. Remember to load this after you loaded the material.js

**Comment by PaysnugAfrica** [comment]
it will be good if they can solve this issue faster

**Comment by f-moya** [comment]
For those who couldn't get the patch working by adding the new `select.js` into your projects, another alternative is to create a build from the main dev branch. I cloned the project, checkout to `v1-dev` and I managed to create a fresh build using yarn and grunt. As done in the CI. Then I just replaced the `materialize.min.js` with the one manually created 👍🏼

**Comment by slawek-kobiec** [comment]
I have managed to fix this issue by modifying source materialize.js file. 
I have commented out scaling in Dropdown functions "_animateIn" and "_animateIn" and either nav dropdowns and form selects started behaving as they should.


![sdf](https://user-images.githubusercontent.com/38790783/106383534-920a0b80-63be-11eb-8d2e-6734b9862cca.png)

**Comment by BWeeks101** [comment]
The fixed select.js was unfortunately not working for me, so I worked around it with the following CSS:

`.select-wrapper * {
    transition: none !important;
    transform: none !important;
}`

**Comment by ignasdamunskis** [comment]
I created a npm package to solve this and other materialize issues
https://www.npmjs.com/package/materialize-css-helper

The idea of this package is not to remove existing functionality (i.e. removing aniamtion as @BWeeks101 suggested), but instead just fix the issue itself.

**Comment by hashcott** [comment]
> The fixed select.js was unfortunately not working for me, so I worked around it with the following CSS:
> 
> `.select-wrapper * { transition: none !important; transform: none !important; }`

it's working

**Comment by YuroKazuma08** [comment]
> 

This one definitely worked.

**Comment by Jero786** [comment]
This issue still happening, it should not be closed. The animation still breaks the Select on IOs mobile device. I was able to resolve this by adding the workaround that @hashcott shared.

**Comment by NilanjPatel** [comment]
> The fixed select.js was unfortunately not working for me, so I worked around it with the following CSS:
> 
> `.select-wrapper * { transition: none !important; transform: none !important; }`

Thank you, its working for me. Can you describe your solution.
