### ISSUE TITLE
Duplicate icons

### ISSUE THREAD

**Issue by Lerie82** [Dogfalo/materialize#6585]
I noticed there are duplicate icons, is there a reason for this?

`<i class="small material-icons">create</i>
<i class="small material-icons">edit</i>`

**Comment by Smankusors** [comment]
Hmm where do you find this?

**Comment by Lerie82** [comment]
Just from the Icons page in the documentation. I needed the two functionalities and found the icons and noticed they were the same. Not really a bug, just kinda wondering. You can totally close this if it's not appropriate.

https://materializecss.com/icons.html

**Comment by Smankusors** [comment]
It's not from Materialize, the docs only mention available material icons provided by Google. So it's better ask Google why it's like that. 

You can also found these icons are same on the official material documentation [here](https://material.io/resources/icons).

IMO, it's better to use `add` instead of `create` in your case

**Comment by Lerie82** [comment]
I chose not to use any icons, but hey my bad, for some reason I thought theses belonged to this repo.
