### ISSUE TITLE
Tabs hover black

### ISSUE THREAD

**Issue by Pantic14** [Dogfalo/materialize#677]
Hi. I've created a table as he says in http://materializecss.com/tabs.html, but when I put on an item in the table is highlighted in black, how can I change that color? I've tried modifying the _tabs.scss but i have not succeed.
Thanks.

**Comment by Dogfalo** [comment]
You need to compile Sass if you use Sass. I do not think there is a problem with tabs.

**Comment by Pantic14** [comment]
I compile with sass but the problem is still here. Has happened to anyone else?

**Comment by emuro2** [comment]
Hey @Pantic14 . I had the same issue and I fixed it! Found the solution on stackoverflow. http://stackoverflow.com/questions/14066798/remove-black-background-when-hovering 

Answer from neilmarion:
the culprit is at assets/stylesheets/scaffolds.css.scss

a {
  color: #000;
  &:visited {
    color: #666;
  }
  &:hover {
    color: #fff;
    background-color: #000;      >=(   change "#000" to "transparent" or what ever color you want
  }
}
