### ISSUE TITLE
Asking the rationale for display:none in parallax img class in your CSS file ... 

### ISSUE THREAD

**Issue by arubyist** [Dogfalo/materialize#705]
Regarding this in your CSS file: 
```.
parallax img {
    bottom: 0;
    display: none;
    position: absolute;
    width: 100%;
}
``` 
Why do you have `display:none`?

It makes the photo in the parallax class disappear every odd while. 

Is it safe to take `display:none` out? I'm asking because I'm quite befuddled why you have that line and I can't discern the reason to leave it in.

I'd like to use this Materialize's framework for a site to be in production eventually but the fact the photo disappears and appears intermittently makes me wary.

**Comment by Dogfalo** [comment]
Display none is there so that the images do not flicker in their position while the javascript is loading. We show the images in the correct position once they are loaded. This is not causing the problem however, in the last update we changed our .load function. But this caused a problem with caching. Once we release the problem will be resolved

**Comment by arubyist** [comment]
Ah. Hope you fix the problem with caching soon! It really drove me bonkers yesterday.
