### ISSUE TITLE
Modal transition doesn't follow Material Design principles

### ISSUE THREAD

**Issue by AndrewCarterUK** [Dogfalo/materialize#721]
When a modal is launched [Material Design spec](http://www.google.co.uk/design/spec/animation/meaningful-transitions.html) states that it should undergo a meaningful transition.

AngularJS Material has their 'Dialog' appearing from (and returning to the button that clicked it) which helps the user understand the journey they are being taken on.

**Comment by EatSalad** [comment]
Hi =)

What do you mean by "doesn't follow Material Design principles"
Please explain. 

http://www.google.com/design/spec/components/dialogs.html#dialogs-specs
They don't really explain dialogs mouvement =/

**Comment by dhawken** [comment]
About the only thing I could see different about this implementation versus others would be the dialog dismissal.  Instead of reversing the transition of the dialog's appearance, it just seems to disappear and the cloaked content is brought back into focus. AngularJS starts their transition from the button that clicked it and the dismissal reverses that.  Lumx however, does a more bootstrappy thing where the dialog comes down from the top and dismissing it reverses that motion.

Is this one wrong?  Not sure; the MD principles are:

"Outgoing elements - elements that are no longer relevant to the new context must be removed from the scene in an appropriate manner."

While these aren't the exact same as other implementations, the dialog isn't necessarily removed in an inappropriate manner to me.  Might be nice to reverse the motion, but I'm not feeling this is a big deal.  On the other hand, side navs do leave the scene nicely in the reverse fashion in which they arrived, so one could argue it would be consistent to make the modals do the same.

**Comment by EatSalad** [comment]
If you at dialog un Android lollipop, dialog like the one chosing your ringtone, there is no such animations. The dialog juste appair ans disappair.

But i think you're right about the fact they don't reverse, it's two different animation ;/

**Comment by AndrewCarterUK** [comment]
One of the material design principles is that elements in motion should undergo meaningful transitions (http://www.google.co.uk/design/spec/animation/meaningful-transitions.html).

To quote:

"Sometimes, it is difficult for a user to know where to look or understand how an element got from point A to point B. Carefully choreographed motion design can effectively guide the user’s attention and focus through multiple steps of a process or procedure, avoid confusion when layouts change or elements are rearranged, and improve the overall beauty of the experience. Motion design should serve a functional purpose."

Simply having the dialog appear on the page is not sufficient as that doesn't help a user understand visually what triggered that action (or how to trigger it again when it disappears).

AngularJS have done this by having the dialog appearing from (and disappearing into) the button that launched it (https://material.angularjs.org/#/demo/material.components.dialog).

**Comment by EatSalad** [comment]
+1

@Dogfalo, i think your team should work on this =)
