### ISSUE TITLE
Problem with responsive-table

### ISSUE THREAD

**Issue by EatSalad** [Dogfalo/materialize#722]
Hi everyone !

I search for hours, but it seems like something broken with responsive-table.
Here an entirely page with a bug table : http://dev.admin.eatsalad.fr/test.html

I already know about my research script : css('display') must be corrected.
But anyway, here's not the problem.

On load, you can't even see the content of table if you're on smartphone.

Thanks ! =)

EDIT : more here : https://gitter.im/Dogfalo/materialize?at=54e48d80516319127575e040
here : https://gitter.im/Dogfalo/materialize?at=54e5fe7448b72ed5309582d2

**Comment by EatSalad** [comment]
It's seems google don't like wrapping our card and responsive-tables ...

On my html :
http://image.noelshack.com/fichiers/2015/08/1424361547-trololo.png

On Demo :
http://image.noelshack.com/fichiers/2015/08/1424361937-troloolololo-ok.png

**Comment by EatSalad** [comment]
Well ... if you add
`<!DOCTYPE html>`
it works, else not ><!

\resolved

**Comment by Dogfalo** [comment]
Interesting, how did you narrow down it was the doctype?

**Comment by yowkah** [comment]
the table, tr and td elements were showing "display: table, table-row or table-cell"  as their display style while the rule it was computing from was saying it had to be display: block. After demolishing everything on the website around the table to see if that was causing any trouble, and knowing it should work since it does work on materializecss.com's example, adding the doctype was the only thing that might influence it. But really, chrome's dev-tools telling us a TD is being displayed as display:table-cell  while also saying that the rules concerning the display property of this element say it should be displayed as block.. well... that kind of was the dead give away.

**Comment by lypef** [comment]
@EatSalad 
you are right, when you add that line and everything fits.
