### ISSUE TITLE
Alignment problem in search navbar

### ISSUE THREAD

**Issue by Krazitchek** [Dogfalo/materialize#931]
Icon on search navbar, left align, is truncated.

![navbar](https://cloud.githubusercontent.com/assets/11500208/6665541/05a192b6-cbdb-11e4-9013-57b1d0455f0d.png)

**Comment by dcworldwide** [comment]
Similar issue for me. My brand text should be left aligned (which it is on a large/medium scale page). When i resize the page to small, the brand text floats to the center of the page instead of the left. 

![screen shot 2015-03-20 at 23 21 09](https://cloud.githubusercontent.com/assets/4898751/6752185/e98b3566-cf57-11e4-89f1-08724c3ee4ee.png)

**Comment by kampfkeks** [comment]
@dcworldwide :

Is it on medium scale also left aligned?
Because on Tablet and Handy screen size the brand gets centered.

To float it to the left, just add the following lines to your css file:
@media only screen and (max-width : 992px) {
nav .brand-logo.left {
      left: 0.5rem;
      padding: 0; 
}
}

@Krazitchek :

Please post a codepen with your code.

**Comment by Krazitchek** [comment]
It's not my code, the screenshot i posted is from Materializecss website:
http://materializecss.com/navbar.html

**Comment by kampfkeks** [comment]
@Krazitchek 

This is an error on the page, its not displayed correctly.
The input tag has always a width of 100%, but the label adds some padding to it so the input is larger than the parent. And because the input is centered on the materialize page, you only see a half of the search icon.

**Comment by dcworldwide** [comment]
Thanks kampfkeks, this helped me.

**Comment by acburst** [comment]
Made clearer in documentation 5384ebc9ba9c8ec22c79bc47cfe69fb414759fc6
